(* JH7110/ClintMsipTest.v -- GENERATED by tools/vtest.  Do not edit: run
   `make vtest` to regenerate.

   THE TEST: the image tools/vtest/tests/clint_msip.S was built to, the hart it
   ran on, the memory that was mapped, and what it was given.  This is the
   EXPERIMENT; what came back is in ClintMsipRun.v.

   THE HART IS 2, and it is not a label: [ColdBoot.cold_regs] is
   parametric in it and the program reads [mhartid], so a model started on
   a different one computes a different stack slot and goes stuck. *)
From Stdlib Require Import List ZArith String.
From stdpp Require Import base list gmap bitvector.definitions.
Import ListNotations.
From VTest Require Import VTest VRun.
Local Open Scope Z_scope.

Module ClintMsip <: TEST.
  Definition name       := "clint_msip"%string.
  Definition platform   := "jh7110"%string.
  Definition hart       : Z := 2.
  Definition regions    : list region := std_regions.
  Definition uart_input : list (uart_id * bv 8) := [].
  Definition disk_init  : list (Z * list Z) := [].

  Definition text : list Z :=
    [15; 16; 0; 0; 243; 34; 64; 241; 147; 130; 226; 255; 55; 3; 8; 0; 27; 3; 19; 9;
   19; 19; 195; 0; 147; 147; 178; 0; 51; 1; 115; 64; 183; 29; 0; 0; 155; 141; 29; 128;
   147; 157; 77; 1; 99; 158; 2; 0; 239; 0; 64; 2; 15; 0; 240; 15; 183; 82; 79; 68;
   155; 130; 82; 228; 35; 160; 93; 0; 111; 0; 0; 0; 239; 0; 128; 0; 111; 0; 0; 0;
   103; 128; 0; 0; 243; 36; 64; 241; 35; 160; 157; 2; 133; 66; 35; 162; 93; 0; 55; 4;
   0; 2; 147; 146; 36; 0; 22; 148; 131; 34; 4; 0; 35; 164; 93; 0; 133; 66; 35; 32;
   84; 0; 131; 34; 4; 0; 35; 166; 93; 0; 243; 34; 64; 52; 147; 242; 130; 0; 35; 168;
   93; 0; 137; 66; 35; 162; 93; 0; 35; 32; 4; 0; 131; 34; 4; 0; 35; 170; 93; 0;
   243; 34; 64; 52; 147; 242; 130; 0; 35; 172; 93; 0; 183; 2; 0; 2; 131; 162; 2; 0;
   35; 174; 93; 0; 141; 66; 35; 162; 93; 0; 130; 128; 0; 0; 0; 0].
End ClintMsip.
