(* JH7110/CoreRegsGprTest.v -- GENERATED by tools/vtest.  Do not edit: run
   `make vtest` to regenerate.

   THE TEST: the image tools/vtest/tests/core_regs_gpr.S was built to, the hart it
   ran on, the memory that was mapped, and what it was given.  This is the
   EXPERIMENT; what came back is in CoreRegsGprRun.v.

   THE HART IS 2, and it is not a label: [ColdBoot.cold_regs] is
   parametric in it and the program reads [mhartid], so a model started on
   a different one computes a different stack slot and goes stuck. *)
From Stdlib Require Import List ZArith String.
From stdpp Require Import base list gmap bitvector.definitions.
Import ListNotations.
From VTest Require Import VTest VRun.
Local Open Scope Z_scope.

Module CoreRegsGpr <: TEST.
  Definition name       := "core_regs_gpr"%string.
  Definition platform   := "jh7110"%string.
  Definition hart       : Z := 2.
  Definition regions    : list region := std_regions.
  Definition uart_input : list (uart_id * bv 8) := [].
  Definition disk_init  : list (Z * list Z) := [].

  Definition text : list Z :=
    [15; 16; 0; 0; 243; 34; 64; 241; 147; 130; 226; 255; 55; 3; 8; 0; 27; 3; 19; 9;
   19; 19; 195; 0; 147; 147; 178; 0; 51; 1; 115; 64; 183; 29; 0; 0; 155; 141; 29; 128;
   147; 157; 77; 1; 99; 158; 2; 0; 239; 0; 64; 2; 15; 0; 240; 15; 183; 82; 79; 68;
   155; 130; 82; 228; 35; 160; 93; 0; 111; 0; 0; 0; 239; 0; 128; 0; 111; 0; 0; 0;
   103; 128; 0; 0; 35; 180; 29; 0; 35; 184; 45; 0; 35; 188; 61; 0; 35; 176; 77; 2;
   35; 180; 93; 2; 35; 184; 109; 2; 35; 188; 125; 2; 35; 176; 141; 4; 35; 180; 157; 4;
   35; 184; 173; 4; 35; 180; 221; 6; 35; 184; 237; 6; 35; 188; 253; 6; 35; 176; 13; 9;
   35; 180; 29; 9; 35; 184; 45; 9; 35; 188; 61; 9; 35; 176; 77; 11; 35; 180; 93; 11;
   35; 184; 109; 11; 35; 188; 125; 11; 35; 176; 141; 13; 35; 180; 157; 13; 35; 184; 173; 13;
   35; 188; 189; 13; 35; 176; 205; 15; 35; 180; 221; 15; 35; 184; 237; 15; 35; 188; 253; 15;
   133; 66; 35; 162; 93; 0; 130; 128; 0; 0; 0; 0].
End CoreRegsGpr.
