(* JH7110/CoreDtbPass.v -- GENERATED by tools/vtest.  Do not edit.

   The proof for the run of case [core_dtb] on platform [jh7110].  What is proved
   is a statement about [RiscvLang.prim_step]; [VExecStep] is what carries a
   computation of the interpreter to it.

   THIS RUN PASSES BECAUSE the model EXHIBITS every observation the platform
   produced, from this test's own configuration. *)
From Stdlib Require Import List ZArith.
From stdpp Require Import base list.
Import ListNotations.
From VTest Require Import VTest VRun VExecStep.
From VTest.JH7110 Require Import CoreDtbTest CoreDtbRun.

Module CoreDtbPass <: TEST_PASSES_AGREE CoreDtb CoreDtbRun.
  Lemma agrees :
    run_agrees CoreDtb.hart CoreDtb.text CoreDtb.regions
               CoreDtb.uart_input CoreDtb.disk_init CoreDtbRun.observed.
  Proof.
    intros o Ho.
    cbn [CoreDtbRun.observed CoreDtbRun.results fmap list_fmap] in Ho.
    repeat (destruct Ho as [<-|Ho];
            [ apply (run_shows false lowest_head 2000 2000);
              vm_cast_no_check (eq_refl true) |]).
    destruct Ho.
  Qed.
End CoreDtbPass.
