(* ------------------------------------------------------------------ *)
(* AUTO-GENERATED by tools/dump_elf.py (--format rocq-syms).           *)
(* Symbol table of xv6-riscv/user/_echo: 48 symbols.
   One [Definition <name> : Z] per symbol -- refer to a symbol's
   address directly as `EchoSyms.<name>` (e.g.
   `EchoSyms.main`). A handful of ELF names aren't valid Rocq
   identifiers as-is (e.g. GCC's `.0`/`.1` static-local disambiguation
   suffixes); those are sanitized (non-ident chars -> `_`), noted below.
                                                                       *)
(* ------------------------------------------------------------------ *)

From Stdlib Require Import ZArith.

Definition main : Z := 0x0%Z.
Definition start : Z := 0x7c%Z.
Definition strcpy : Z := 0x8c%Z.
Definition strcmp : Z := 0xac%Z.
Definition strlen : Z := 0xdc%Z.
Definition memset : Z := 0x108%Z.
Definition strchr : Z := 0x12e%Z.
Definition gets : Z := 0x156%Z.
Definition stat : Z := 0x1cc%Z.
Definition atoi : Z := 0x208%Z.
Definition memmove : Z := 0x254%Z.
Definition memcmp : Z := 0x2b0%Z.
Definition memcpy : Z := 0x2ea%Z.
Definition sbrk : Z := 0x2fe%Z.
Definition sbrklazy : Z := 0x314%Z.
Definition fork : Z := 0x32a%Z.
Definition exit : Z := 0x332%Z.
Definition wait : Z := 0x33a%Z.
Definition pipe : Z := 0x342%Z.
Definition read : Z := 0x34a%Z.
Definition write : Z := 0x352%Z.
Definition close : Z := 0x35a%Z.
Definition kill : Z := 0x362%Z.
Definition exec : Z := 0x36a%Z.
Definition open : Z := 0x372%Z.
Definition mknod : Z := 0x37a%Z.
Definition unlink : Z := 0x382%Z.
Definition fstat : Z := 0x38a%Z.
Definition link : Z := 0x392%Z.
Definition mkdir : Z := 0x39a%Z.
Definition chdir : Z := 0x3a2%Z.
Definition dup : Z := 0x3aa%Z.
Definition getpid : Z := 0x3b2%Z.
Definition sys_sbrk : Z := 0x3ba%Z.
Definition pause : Z := 0x3c2%Z.
Definition uptime : Z := 0x3ca%Z.
Definition sync : Z := 0x3d2%Z.
Definition seccomp : Z := 0x3da%Z.
Definition putc : Z := 0x3e2%Z.
Definition printint : Z := 0x400%Z.
Definition vprintf : Z := 0x49e%Z.
Definition fprintf : Z := 0x75e%Z.
Definition printf : Z := 0x788%Z.
Definition free : Z := 0x7ba%Z.
Definition malloc : Z := 0x840%Z.
Definition digits : Z := 0x958%Z.
Definition freep : Z := 0x1000%Z.
Definition base : Z := 0x1010%Z.

(* Total symbols = 48. *)
