/Require/!s/\bgmap_curry\b/map_curry/g
/Require/!s/\bgmap_uncurry\b/map_uncurry/g
/Require/!s/\blookup_gmap_uncurry\b/lookup_map_uncurry/g
/Require/!s/\blookup_gmap_curry\b/lookup_map_curry/g
/Require/!s/\blookup_gmap_curry_None\b/lookup_map_curry_None/g
/Require/!s/\bgmap_uncurry_curry\b/map_uncurry_curry/g
/Require/!s/\bgmap_curry_non_empty\b/map_curry_non_empty/g
/Require/!s/\bgmap_curry_uncurry_non_empty\b/map_curry_uncurry_non_empty/g
/Require/!s/\blookup_partial_alter\b/lookup_partial_alter_eq/g
/Require/!s/\blookup_total_partial_alter\b/lookup_total_partial_alter_eq/g
/Require/!s/\blookup_alter\b/lookup_alter_eq/g
/Require/!s/\blookup_delete\b/lookup_delete_eq/g
/Require/!s/\blookup_total_delete\b/lookup_total_delete_eq/g
/Require/!s/\blookup_insert\b/lookup_insert_eq/g
/Require/!s/\blookup_total_insert\b/lookup_total_insert_eq/g
/Require/!s/\blookup_singleton\b/lookup_singleton_eq/g
/Require/!s/\blookup_total_singleton\b/lookup_total_singleton_eq/g
/Require/!s/\bpartial_alter_compose\b/partial_alter_partial_alter_eq/g
/Require/!s/\bpartial_alter_commute\b/partial_alter_partial_alter_ne/g
/Require/!s/\balter_compose\b/alter_alter_eq/g
/Require/!s/\balter_commute\b/alter_alter_ne/g
/Require/!s/\bdelete_commute\b/delete_delete/g
/Require/!s/\bdelete_idemp\b/delete_delete_eq/g
/Require/!s/\binsert_insert\b/insert_insert_eq/g
/Require/!s/\binsert_commute\b/insert_insert_ne/g
/Require/!s/\balter_insert\b/alter_insert_eq/g
/Require/!s/\bdelete_insert\b/delete_insert_id/g
/Require/!s/\bdelete_insert_delete\b/delete_insert_eq/g
/Require/!s/\bdelete_alter\b/delete_alter_eq/g
/Require/!s/\binsert_delete_insert\b/insert_delete_eq/g
/Require/!s/\binsert_delete\b/insert_delete_id/g
/Require/!s/\bdelete_alter\b/delete_alter_eq/g
/Require/!s/\balter_singleton\b/alter_singleton_eq/g
/Require/!s/\bdelete_singleton\b/delete_singleton_eq/g
/Require/!s/\binsert_singleton\b/insert_singleton_eq/g
/Require/!s/\bfoldr_delete_commute\b/delete_foldr_delete/g
/Require/!s/\bfoldr_delete_notin\b/foldr_delete_id/g
/Require/!s/\bfoldr_delete_insert\b/foldr_delete_insert_in/g
/Require/!s/\bfoldr_delete_insert_ne\b/foldr_delete_insert_notin/g
/Require/!s/\bdelete_notin\b/delete_id/g
/Require/!s/\bpartial_alter_self_alt\b/partial_alter_id/g
/Require/!s/\bmultiplicity_singleton\b/multiplicity_singleton_eq/g
/Require/!s/\bmultiplicity_singleton'\b/multiplicity_singleton/g
/Require/!s/\blist_lookup_insert\b/list_lookup_insert_eq/g
/Require/!s/\blist_lookup_total_insert\b/list_lookup_total_insert_eq/g
/Require/!s/\blist_lookup_alter\b/list_lookup_alter_eq/g
/Require/!s/\blist_lookup_total_alter\b/list_lookup_total_alter_eq/g
/Require/!s/\blookup_delete_lt\b/list_lookup_delete_lt/g
/Require/!s/\blookup_delete_ge\b/list_lookup_delete_ge/g
/Require/!s/\blookup_total_delete_lt\b/list_lookup_total_delete_lt/g
/Require/!s/\blookup_total_delete_ge\b/list_lookup_total_delete_ge/g
/Require/!s/\blookup_take\b/lookup_take_lt/g
/Require/!s/\blookup_total_take\b/lookup_total_take_lt/g
/Require/!s/\blist_insert_insert\b/list_insert_insert_eq/g
/Require/!s/\blist_insert_commute\b/list_insert_insert_ne/g
/Require/!s/\blist_alter_compose\b/list_alter_alter_eq/g
/Require/!s/\blist_alter_commute\b/list_alter_alter_eq/g
/Require/!s/\btake_insert\b/take_insert_ge/g
/Require/!s/\btake_alter\b/take_alter_ge/g
/Require/!s/\bdrop_alter\b/drop_alter_lt/g
/Require/!s/\bdrop_insert_le\b/drop_insert_ge/g
/Require/!s/\bdrop_insert_gt\b/drop_insert_lt/g
/Require/!s/\bdecompose_elem_of_list\b/decompose_list_elem_of/g
/Require/!s/\belem_of_list\b/list_elem_of/g
/Require/!s/\belem_of_list_here\b/list_elem_of_here/g
/Require/!s/\belem_of_list_further\b/list_elem_of_further/g
/Require/!s/\belem_of_list_In\b/list_elem_of_In/g
/Require/!s/\belem_of_list_singleton\b/list_elem_of_singleton/g
/Require/!s/\belem_of_list_lookup_1\b/list_elem_of_lookup_1/g
/Require/!s/\belem_of_list_lookup_total_1\b/list_elem_of_lookup_total_1/g
/Require/!s/\belem_of_list_lookup_2\b/list_elem_of_lookup_2/g
/Require/!s/\belem_of_list_lookup_total_2\b/list_elem_of_lookup_total_2/g
/Require/!s/\belem_of_list_lookup\b/list_elem_of_lookup/g
/Require/!s/\belem_of_list_lookup_total\b/list_elem_of_lookup_total/g
/Require/!s/\belem_of_list_split_length\b/list_elem_of_split_length/g
/Require/!s/\belem_of_list_split\b/list_elem_of_split/g
/Require/!s/\belem_of_list_split_l\b/list_elem_of_split_l/g
/Require/!s/\belem_of_list_split_r\b/list_elem_of_split_r/g
/Require/!s/\belem_of_list_intersection_with\b/list_elem_of_intersection_with/g
/Require/!s/\belem_of_list_difference\b/list_elem_of_difference/g
/Require/!s/\belem_of_list_union\b/list_elem_of_union/g
/Require/!s/\belem_of_list_intersection\b/list_elem_of_intersection/g
/Require/!s/\belem_of_list_filter\b/list_elem_of_filter/g
/Require/!s/\belem_of_list_fmap\b/list_elem_of_fmap/g
/Require/!s/\belem_of_list_fmap_1\b/list_elem_of_fmap_2/g
/Require/!s/\belem_of_list_fmap_2\b/list_elem_of_fmap_1/g
/Require/!s/\belem_of_list_fmap_1_alt\b/list_elem_of_fmap_2'/g
/Require/!s/\belem_of_list_fmap_inj\b/list_elem_of_fmap_inj/g
/Require/!s/\belem_of_list_fmap_2_inj\b/list_elem_of_fmap_inj_2/g
/Require/!s/\belem_of_list_omap\b/list_elem_of_omap/g
/Require/!s/\belem_of_list_bind\b/list_elem_of_bind/g
/Require/!s/\belem_of_list_ret\b/list_elem_of_ret/g
/Require/!s/\belem_of_list_join\b/list_elem_of_join/g
/Require/!s/\belem_of_list_dec\b/list_elem_of_dec/g
/Require/!s/\blist_lookup_fmap_inv\b/list_lookup_fmap_Some_1/g
/Require/!s/\blist_alter_fmap\b/list_fmap_alter/g
/Require/!s/\blist_alter_fmap_mono\b/list_fmap_alter/g
/Require/!s/\bmap_disjoint_difference_l\b/map_disjoint_difference_l1/g
/Require/!s/\bmap_disjoint_difference_r\b/map_disjoint_difference_r1/g
/Require/!s/\blist_delete_subseteq\b/list_subseteq_delete/g
/Require/!s/\blist_filter_subseteq\b/list_subseteq_filter/g
/Require/!s/\bgmultiset_disj_union_list_proper\b/gmultiset_disj_union_list_permutation_proper/g
/Require/!s/\bfilter_singleton\b/filter_singleton_True/g
/Require/!s/\bfilter_singleton_not\b/filter_singleton_False/g
/Require/!s/\bcoPset_suffixes_infinite\b/coPset_suffixes_not_finite/g
/Require/!s/\bnclose_infinite\b/nclose_not_finite/g
/Require/!s/\bimpl_transitive\b/impl_trans/g
/Require/!s/\bprod_lexico_transitive\b/prod_lexico_trans/g
/Require/!s/\bForall2_transitive\b/Forall2_trans/g
/Require/!s/\bstrict_transitive_l\b/strict_trans_l/g
/Require/!s/\bstrict_transitive_r\b/strict_trans_r/g
/Require/!s/\brtc_transitive\b/rtc_trans/g
/Require/!s/\btc_transitive\b/tc_trans/g
/Require/!s/\bmap_empty_interaction\b/map_empty_intersection/g
/Require/!s/\bmap_interaction_empty\b/map_intersection_empty/g
/Require/!s/\bmap_interaction_assoc\b/map_intersection_assoc/g
/Require/!s/\bvlookup_insert_self\b/vlookup_insert_id/g
/Require/!s/\bvlookup_insert\b/vlookup_insert_eq/g
/Require/!s/\bvinsert\b/insert/g
/Require/!s/\bagree_validI\b/agree_op_invI/g
/Require/!s/\b(uPred.)?discrete_valid\b/internal_cmra_valid_discrete/g
/Require/!s/\b(uPred.)?plainly_cmra_valid\b/plainly_internal_cmra_valid/g
/Require/!s/\b(uPred.)?intuitionistically_cmra_valid\b/intuitionistically_internal_cmra_valid/g
# @-explicit uses (an instance passed by hand): on master ghost_var_frac / mono_nat_auth_own_frac are
# NOTATIONS (γ q x := _ γ (DfracOwn q) x), so spell their unfolding instead; _KEEP protects the
# name from the plain renames below and is stripped at the end (found 2026-09-29, SystemAdequacy).
/Require/!s/@ghost_var (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) /@ghost_var_KEEP \1 \3 \5 \7 (DfracOwn \9) /g
/Require/!s/@mono_nat_auth_own (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) /@mono_nat_auth_own_KEEP \1 \3 \5 (DfracOwn \7) /g
/Require/!s/\bghost_var \(ghost_varG0 := ([^)]*)\) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) /ghost_var_KEEP (ghost_varG0 := \1) \2 (DfracOwn \4) /g
/Require/!s/\bmono_nat_auth_own \(mono_natG0 := ([^)]*)\) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) (\([^()]*(\([^()]*\))?[^()]*\)|[^ ()]+) /mono_nat_auth_own_KEEP (mono_natG0 := \1) \2 (DfracOwn \4) /g
/Require/!s/\bghost_var\b/ghost_var_frac/g
/Require/!s/\bghost_map_auth\b/ghost_map_auth_frac/g
/Require/!s/\bmono_nat_auth_own\b/mono_nat_auth_own_frac/g
/Require/!s/\bmono_Z_auth_own\b/mono_Z_auth_own_frac/g
/Require/!s/\bmono_nat_lb_own_valid\b/mono_nat_auth_lb_own_valid/g
/Require/!s/\bmono_Z_lb_own_valid\b/mono_Z_auth_lb_own_valid/g
/Require/!s/\bcmra_morphism_monotone(N|)\b/cmra_morphism_mono\1/g
/Require/!s/\bfupd_soundness_gen\b/fupd_soundness/g
/Require/!s/\bfupd_soundness_lc\b/fupd_soundness HasLc/g
/Require/!s/\bfupd_soundness_no_lc\b/fupd_soundness HasNoLc/g
/Require/!s/\bstep_fupdN_soundness_gen\b/step_fupdN_soundness/g
/Require/!s/\bstep_fupdN_soundness_lc\b/step_fupdN_soundness HasLc/g
/Require/!s/\bstep_fupdN_soundness_no_lc\b/step_fupdN_soundness HasNoLc/g
/Require/!s/\bstep_fupdN_soundness_lc'\b/step_fupdN_soundness HasLc/g
/Require/!s/\bstep_fupdN_soundness_no_lc'\b/step_fupdN_soundness HasNoLc/g
/Require/!s/\bcoq_tactics\b/rocq_tactics/g
/Require/!s/\blater_laterN\b/laterN_succ_l/g
/Require/!s/\blaterN_later\b/laterN_succ_r/g
s/_KEEP\b//g
