(* CodeSafestrcpy.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's safestrcpy: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [sscp_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
From iris.program_logic Require Import language.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode01.
Require Import KernelDecode04.
Require Import KernelDecode06.
Require Import KernelDecode07.
Require Import KernelDecode11.
Require Import KernelDecode13.
Require Import KernelDecode14.
Require Import KernelDecode16.
Require Import KernelDecode17.
Require Import KernelDecode21.
Require Import KernelDecode24.
Require Import KernelDecode27.
Require Import KernelDecode29.
Require Import KernelDecode30.
Require Import KernelDecode31.
Local Open Scope Z_scope.
Import Defs.


Section CodeSafestrcpy.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- safestrcpy @ KernelSyms.safestrcpy, 54 bytes ---- *)

  Lemma sscp_00 : kernel_text -∗ instr (mword_of_int KernelSyms.safestrcpy : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc KernelSyms.safestrcpy (mword_of_int 0x1141 : mword 16)
    (mword_of_int KernelSyms.safestrcpy : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1141 exec_execute_C_ADDI. Qed.

  Lemma sscp_02 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x2) (mword_of_int 0xe406 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_e406 exec_execute_C_SDSP. Qed.

  Lemma sscp_04 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x4) (mword_of_int 0xe022 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e022 exec_execute_C_SDSP. Qed.

  Lemma sscp_06 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x6) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x6) (mword_of_int 0x0800 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x6) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_0800 exec_execute_C_ADDI4SPN. Qed.

  Lemma sscp_08 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x8) : mword 64) false (BTYPE (mword_of_int 38 : mword 13, Regidx (mword_of_int 12), zreg, BGE)).
  Proof using . mk_base (KernelSyms.safestrcpy + 0x8) (mword_of_int 0x02c05363 : mword 32)
    (mword_of_int (KernelSyms.safestrcpy + 0x8) : mword 64) (BTYPE (mword_of_int 38 : mword 13, Regidx (mword_of_int 12), zreg, BGE)) kd_02c05363. Qed.

  Lemma sscp_0c : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0xc) : mword 64) false (ADDIW (mword_of_int 4095 : mword 12, Regidx (mword_of_int 12), Regidx (mword_of_int 13))).
  Proof using . mk_base (KernelSyms.safestrcpy + 0xc) (mword_of_int 0xfff6069b : mword 32)
    (mword_of_int (KernelSyms.safestrcpy + 0xc) : mword 64) (ADDIW (mword_of_int 4095 : mword 12, Regidx (mword_of_int 12), Regidx (mword_of_int 13))) kd_fff6069b. Qed.

  Lemma sscp_10 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x10) : mword 64) true (SHIFTIOP (mword_of_int 32 : mword 6, Regidx (mword_of_int 13), Regidx (mword_of_int 13), SLLI)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x10) (mword_of_int 0x1682 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x10) : mword 64) (SHIFTIOP (mword_of_int 32 : mword 6, Regidx (mword_of_int 13), Regidx (mword_of_int 13), SLLI)) kd_1682 exec_execute_C_SLLI. Qed.

  Lemma sscp_12 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x12) : mword 64) true (SHIFTIOP (mword_of_int 32 : mword 6, creg2reg_idx (Cregidx (mword_of_int 5)), creg2reg_idx (Cregidx (mword_of_int 5)), SRLI)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x12) (mword_of_int 0x9281 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x12) : mword 64) (SHIFTIOP (mword_of_int 32 : mword 6, creg2reg_idx (Cregidx (mword_of_int 5)), creg2reg_idx (Cregidx (mword_of_int 5)), SRLI)) kd_9281 exec_execute_C_SRLI. Qed.

  Lemma sscp_14 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x14) : mword 64) true (RTYPE (Regidx (mword_of_int 11), Regidx (mword_of_int 13), Regidx (mword_of_int 13), ADD)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x14) (mword_of_int 0x96ae : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x14) : mword 64) (RTYPE (Regidx (mword_of_int 11), Regidx (mword_of_int 13), Regidx (mword_of_int 13), ADD)) kd_96ae exec_execute_C_ADD. Qed.

  Lemma sscp_16 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x16) : mword 64) true (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 15), ADD)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x16) (mword_of_int 0x87aa : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x16) : mword 64) (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 15), ADD)) kd_87aa exec_execute_C_MV. Qed.

  Lemma sscp_18 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x18) : mword 64) false (BTYPE (mword_of_int 18 : mword 13, Regidx (mword_of_int 13), Regidx (mword_of_int 11), BEQ)).
  Proof using . mk_base (KernelSyms.safestrcpy + 0x18) (mword_of_int 0x00d58963 : mword 32)
    (mword_of_int (KernelSyms.safestrcpy + 0x18) : mword 64) (BTYPE (mword_of_int 18 : mword 13, Regidx (mword_of_int 13), Regidx (mword_of_int 11), BEQ)) kd_00d58963. Qed.

  Lemma sscp_1c : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x1c) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADDI)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x1c) (mword_of_int 0x0585 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x1c) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADDI)) kd_0585 exec_execute_C_ADDI. Qed.

  Lemma sscp_1e : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x1e) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x1e) (mword_of_int 0x0785 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x1e) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)) kd_0785 exec_execute_C_ADDI. Qed.

  Lemma sscp_20 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x20) : mword 64) false (LOAD (mword_of_int 4095 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 14), true, 1)).
  Proof using . mk_base (KernelSyms.safestrcpy + 0x20) (mword_of_int 0xfff5c703 : mword 32)
    (mword_of_int (KernelSyms.safestrcpy + 0x20) : mword 64) (LOAD (mword_of_int 4095 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 14), true, 1)) kd_fff5c703. Qed.

  Lemma sscp_24 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x24) : mword 64) false (STORE (mword_of_int 4095 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 1)).
  Proof using . mk_base (KernelSyms.safestrcpy + 0x24) (mword_of_int 0xfee78fa3 : mword 32)
    (mword_of_int (KernelSyms.safestrcpy + 0x24) : mword 64) (STORE (mword_of_int 4095 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 1)) kd_fee78fa3. Qed.

  Lemma sscp_28 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x28) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 248 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 6)), BNE)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x28) (mword_of_int 0xfb65 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x28) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 248 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 6)), BNE)) kd_fb65 exec_execute_C_BNEZ. Qed.

  Lemma sscp_2a : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x2a) : mword 64) false (STORE (mword_of_int 0 : mword 12, zreg, Regidx (mword_of_int 15), 1)).
  Proof using . mk_base (KernelSyms.safestrcpy + 0x2a) (mword_of_int 0x00078023 : mword 32)
    (mword_of_int (KernelSyms.safestrcpy + 0x2a) : mword 64) (STORE (mword_of_int 0 : mword 12, zreg, Regidx (mword_of_int 15), 1)) kd_00078023. Qed.

  Lemma sscp_2e : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x2e) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x2e) (mword_of_int 0x60a2 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x2e) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_60a2 exec_execute_C_LDSP. Qed.

  Lemma sscp_30 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x30) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x30) (mword_of_int 0x6402 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x30) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_6402 exec_execute_C_LDSP. Qed.

  Lemma sscp_32 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x32) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x32) (mword_of_int 0x0141 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x32) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_0141 exec_execute_C_ADDI. Qed.

  Lemma sscp_34 : kernel_text -∗ instr (mword_of_int (KernelSyms.safestrcpy + 0x34) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof using . mk_rvc (KernelSyms.safestrcpy + 0x34) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.safestrcpy + 0x34) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

End CodeSafestrcpy.
