(* CodeTrapinit.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's trapinit: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [tri_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
From iris.program_logic Require Import language.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode01.
Require Import KernelDecode05.
Require Import KernelDecode06.
Require Import KernelDecode07.
Require Import KernelDecode09.
Require Import KernelDecode11.
Require Import KernelDecode13.
Require Import KernelDecode14.
Require Import KernelDecode17.
Require Import KernelDecode24.
Require Import KernelDecode28.
Require Import KernelDecode31.
Local Open Scope Z_scope.
Import Defs.


Section CodeTrapinit.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- trapinit @ KernelSyms.trapinit, 36 bytes ---- *)

  Lemma tri_00 : kernel_text -∗ instr (mword_of_int KernelSyms.trapinit : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc KernelSyms.trapinit (mword_of_int 0x1141 : mword 16)
    (mword_of_int KernelSyms.trapinit : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1141 exec_execute_C_ADDI. Qed.

  Lemma tri_02 : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof using . mk_rvc (KernelSyms.trapinit + 0x2) (mword_of_int 0xe406 : mword 16)
    (mword_of_int (KernelSyms.trapinit + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_e406 exec_execute_C_SDSP. Qed.

  Lemma tri_04 : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof using . mk_rvc (KernelSyms.trapinit + 0x4) (mword_of_int 0xe022 : mword 16)
    (mword_of_int (KernelSyms.trapinit + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e022 exec_execute_C_SDSP. Qed.

  Lemma tri_06 : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x6) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof using . mk_rvc (KernelSyms.trapinit + 0x6) (mword_of_int 0x0800 : mword 16)
    (mword_of_int (KernelSyms.trapinit + 0x6) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_0800 exec_execute_C_ADDI4SPN. Qed.

  Lemma tri_08 : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x8) : mword 64) false (UTYPE (mword_of_int 5 : mword 20, Regidx (mword_of_int 11), AUIPC)).
  Proof using . mk_base (KernelSyms.trapinit + 0x8) (mword_of_int 0x00005597 : mword 32)
    (mword_of_int (KernelSyms.trapinit + 0x8) : mword 64) (UTYPE (mword_of_int 5 : mword 20, Regidx (mword_of_int 11), AUIPC)) kd_00005597. Qed.

  Lemma tri_0c : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0xc) : mword 64) false (ITYPE (mword_of_int 3420 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADDI)).
  Proof using . mk_base (KernelSyms.trapinit + 0xc) (mword_of_int 0xd5c58593 : mword 32)
    (mword_of_int (KernelSyms.trapinit + 0xc) : mword 64) (ITYPE (mword_of_int 3420 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADDI)) kd_d5c58593. Qed.

  Lemma tri_10 : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x10) : mword 64) false (UTYPE (mword_of_int 22 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof using . mk_base (KernelSyms.trapinit + 0x10) (mword_of_int 0x00016517 : mword 32)
    (mword_of_int (KernelSyms.trapinit + 0x10) : mword 64) (UTYPE (mword_of_int 22 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00016517. Qed.

  Lemma tri_14 : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x14) : mword 64) false (ITYPE (mword_of_int 3956 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof using . mk_base (KernelSyms.trapinit + 0x14) (mword_of_int 0xf7450513 : mword 32)
    (mword_of_int (KernelSyms.trapinit + 0x14) : mword 64) (ITYPE (mword_of_int 3956 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_f7450513. Qed.

  Lemma tri_18 : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x18) : mword 64) false (JAL (mword_of_int 2090676 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.trapinit + 0x18) (mword_of_int 0xeb4fe0ef : mword 32)
    (mword_of_int (KernelSyms.trapinit + 0x18) : mword 64) (JAL (mword_of_int 2090676 : mword 21, Regidx (mword_of_int 1))) kd_eb4fe0ef. Qed.

  Lemma tri_1c : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x1c) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof using . mk_rvc (KernelSyms.trapinit + 0x1c) (mword_of_int 0x60a2 : mword 16)
    (mword_of_int (KernelSyms.trapinit + 0x1c) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_60a2 exec_execute_C_LDSP. Qed.

  Lemma tri_1e : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x1e) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof using . mk_rvc (KernelSyms.trapinit + 0x1e) (mword_of_int 0x6402 : mword 16)
    (mword_of_int (KernelSyms.trapinit + 0x1e) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_6402 exec_execute_C_LDSP. Qed.

  Lemma tri_20 : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x20) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc (KernelSyms.trapinit + 0x20) (mword_of_int 0x0141 : mword 16)
    (mword_of_int (KernelSyms.trapinit + 0x20) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_0141 exec_execute_C_ADDI. Qed.

  Lemma tri_22 : kernel_text -∗ instr (mword_of_int (KernelSyms.trapinit + 0x22) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof using . mk_rvc (KernelSyms.trapinit + 0x22) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.trapinit + 0x22) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

End CodeTrapinit.
