(* CodeSysWait.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's sys_wait: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [swi_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
From iris.program_logic Require Import language.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode00.
Require Import KernelDecode04.
Require Import KernelDecode08.
Require Import KernelDecode10.
Require Import KernelDecode13.
Require Import KernelDecode14.
Require Import KernelDecode15.
Require Import KernelDecode19.
Require Import KernelDecode21.
Require Import KernelDecode27.
Local Open Scope Z_scope.
Import Defs.


Section CodeSysWait.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- sys_wait @ KernelSyms.sys_wait, 34 bytes ---- *)

  Lemma swi_00 : kernel_text -∗ instr (mword_of_int KernelSyms.sys_wait : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc KernelSyms.sys_wait (mword_of_int 0x1101 : mword 16)
    (mword_of_int KernelSyms.sys_wait : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1101 exec_execute_C_ADDI. Qed.

  Lemma swi_02 : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof using . mk_rvc (KernelSyms.sys_wait + 0x2) (mword_of_int 0xec06 : mword 16)
    (mword_of_int (KernelSyms.sys_wait + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_ec06 exec_execute_C_SDSP. Qed.

  Lemma swi_04 : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof using . mk_rvc (KernelSyms.sys_wait + 0x4) (mword_of_int 0xe822 : mword 16)
    (mword_of_int (KernelSyms.sys_wait + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e822 exec_execute_C_SDSP. Qed.

  Lemma swi_06 : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x6) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof using . mk_rvc (KernelSyms.sys_wait + 0x6) (mword_of_int 0x1000 : mword 16)
    (mword_of_int (KernelSyms.sys_wait + 0x6) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_1000 exec_execute_C_ADDI4SPN. Qed.

  Lemma swi_08 : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x8) : mword 64) false (ITYPE (mword_of_int 4072 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 11), ADDI)).
  Proof using . mk_base (KernelSyms.sys_wait + 0x8) (mword_of_int 0xfe840593 : mword 32)
    (mword_of_int (KernelSyms.sys_wait + 0x8) : mword 64) (ITYPE (mword_of_int 4072 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 11), ADDI)) kd_fe840593. Qed.

  Lemma swi_0c : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0xc) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 0 : mword 6), zreg, Regidx (mword_of_int 10), ADDI)).
  Proof using . mk_rvc (KernelSyms.sys_wait + 0xc) (mword_of_int 0x4501 : mword 16)
    (mword_of_int (KernelSyms.sys_wait + 0xc) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 0 : mword 6), zreg, Regidx (mword_of_int 10), ADDI)) kd_4501 exec_execute_C_LI. Qed.

  Lemma swi_0e : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0xe) : mword 64) false (JAL (mword_of_int 2096872 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.sys_wait + 0xe) (mword_of_int 0xee9ff0ef : mword 32)
    (mword_of_int (KernelSyms.sys_wait + 0xe) : mword 64) (JAL (mword_of_int 2096872 : mword 21, Regidx (mword_of_int 1))) kd_ee9ff0ef. Qed.

  Lemma swi_12 : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x12) : mword 64) false (LOAD (mword_of_int 4072 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 10), false, 8)).
  Proof using . mk_base (KernelSyms.sys_wait + 0x12) (mword_of_int 0xfe843503 : mword 32)
    (mword_of_int (KernelSyms.sys_wait + 0x12) : mword 64) (LOAD (mword_of_int 4072 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 10), false, 8)) kd_fe843503. Qed.

  Lemma swi_16 : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x16) : mword 64) false (JAL (mword_of_int 2095102 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.sys_wait + 0x16) (mword_of_int 0xffeff0ef : mword 32)
    (mword_of_int (KernelSyms.sys_wait + 0x16) : mword 64) (JAL (mword_of_int 2095102 : mword 21, Regidx (mword_of_int 1))) kd_ffeff0ef. Qed.

  Lemma swi_1a : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x1a) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof using . mk_rvc (KernelSyms.sys_wait + 0x1a) (mword_of_int 0x60e2 : mword 16)
    (mword_of_int (KernelSyms.sys_wait + 0x1a) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_60e2 exec_execute_C_LDSP. Qed.

  Lemma swi_1c : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x1c) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof using . mk_rvc (KernelSyms.sys_wait + 0x1c) (mword_of_int 0x6442 : mword 16)
    (mword_of_int (KernelSyms.sys_wait + 0x1c) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_6442 exec_execute_C_LDSP. Qed.

  Lemma swi_1e : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x1e) : mword 64) true (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)).
  Proof using . mk_rvc (KernelSyms.sys_wait + 0x1e) (mword_of_int 0x6105 : mword 16)
    (mword_of_int (KernelSyms.sys_wait + 0x1e) : mword 64) (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)) kd_6105 exec_execute_C_ADDI16SP. Qed.

  Lemma swi_20 : kernel_text -∗ instr (mword_of_int (KernelSyms.sys_wait + 0x20) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof using . mk_rvc (KernelSyms.sys_wait + 0x20) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.sys_wait + 0x20) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

End CodeSysWait.
