(* CodeKvminithart.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's kvminithart: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [kvi_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
From iris.program_logic Require Import language.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode01.
Require Import KernelDecode04.
Require Import KernelDecode06.
Require Import KernelDecode07.
Require Import KernelDecode11.
Require Import KernelDecode12.
Require Import KernelDecode13.
Require Import KernelDecode14.
Require Import KernelDecode15.
Require Import KernelDecode16.
Require Import KernelDecode17.
Require Import KernelDecode20.
Require Import KernelDecode24.
Require Import KernelDecode26.
Require Import KernelDecode31.
Local Open Scope Z_scope.
Import Defs.


Section CodeKvminithart.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- kvminithart @ KernelSyms.kvminithart, 44 bytes ---- *)

  Lemma kvi_00 : kernel_text -∗ instr (mword_of_int KernelSyms.kvminithart : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc KernelSyms.kvminithart (mword_of_int 0x1141 : mword 16)
    (mword_of_int KernelSyms.kvminithart : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1141 exec_execute_C_ADDI. Qed.

  Lemma kvi_02 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x2) (mword_of_int 0xe406 : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_e406 exec_execute_C_SDSP. Qed.

  Lemma kvi_04 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x4) (mword_of_int 0xe022 : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e022 exec_execute_C_SDSP. Qed.

  Lemma kvi_06 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x6) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x6) (mword_of_int 0x0800 : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x6) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_0800 exec_execute_C_ADDI4SPN. Qed.

  Lemma kvi_08 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x8) : mword 64) false (SFENCE_VMA (zreg, zreg)).
  Proof using . mk_base (KernelSyms.kvminithart + 0x8) (mword_of_int 0x12000073 : mword 32)
    (mword_of_int (KernelSyms.kvminithart + 0x8) : mword 64) (SFENCE_VMA (zreg, zreg)) kd_12000073. Qed.

  Lemma kvi_0c : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0xc) : mword 64) false (UTYPE (mword_of_int 9 : mword 20, Regidx (mword_of_int 15), AUIPC)).
  Proof using . mk_base (KernelSyms.kvminithart + 0xc) (mword_of_int 0x00009797 : mword 32)
    (mword_of_int (KernelSyms.kvminithart + 0xc) : mword 64) (UTYPE (mword_of_int 9 : mword 20, Regidx (mword_of_int 15), AUIPC)) kd_00009797. Qed.

  Lemma kvi_10 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x10) : mword 64) false (LOAD (mword_of_int 986 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), false, 8)).
  Proof using . mk_base (KernelSyms.kvminithart + 0x10) (mword_of_int 0x3da7b783 : mword 32)
    (mword_of_int (KernelSyms.kvminithart + 0x10) : mword 64) (LOAD (mword_of_int 986 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), false, 8)) kd_3da7b783. Qed.

  Lemma kvi_14 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x14) : mword 64) true (SHIFTIOP (mword_of_int 12 : mword 6, creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), SRLI)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x14) (mword_of_int 0x83b1 : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x14) : mword 64) (SHIFTIOP (mword_of_int 12 : mword 6, creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), SRLI)) kd_83b1 exec_execute_C_SRLI. Qed.

  Lemma kvi_16 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x16) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 63 : mword 6), zreg, Regidx (mword_of_int 14), ADDI)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x16) (mword_of_int 0x577d : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x16) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 63 : mword 6), zreg, Regidx (mword_of_int 14), ADDI)) kd_577d exec_execute_C_LI. Qed.

  Lemma kvi_18 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x18) : mword 64) true (SHIFTIOP (mword_of_int 63 : mword 6, Regidx (mword_of_int 14), Regidx (mword_of_int 14), SLLI)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x18) (mword_of_int 0x177e : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x18) : mword 64) (SHIFTIOP (mword_of_int 63 : mword 6, Regidx (mword_of_int 14), Regidx (mword_of_int 14), SLLI)) kd_177e exec_execute_C_SLLI. Qed.

  Lemma kvi_1a : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x1a) : mword 64) true (RTYPE (creg2reg_idx (Cregidx (mword_of_int 6)), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), OR)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x1a) (mword_of_int 0x8fd9 : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x1a) : mword 64) (RTYPE (creg2reg_idx (Cregidx (mword_of_int 6)), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), OR)) kd_8fd9 ke_8fd9. Qed.

  Lemma kvi_1c : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x1c) : mword 64) false (CSRReg (mword_of_int 384 : mword 12, Regidx (mword_of_int 15), zreg, CSRRW)).
  Proof using . mk_base (KernelSyms.kvminithart + 0x1c) (mword_of_int 0x18079073 : mword 32)
    (mword_of_int (KernelSyms.kvminithart + 0x1c) : mword 64) (CSRReg (mword_of_int 384 : mword 12, Regidx (mword_of_int 15), zreg, CSRRW)) kd_18079073. Qed.

  Lemma kvi_20 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x20) : mword 64) false (SFENCE_VMA (zreg, zreg)).
  Proof using . mk_base (KernelSyms.kvminithart + 0x20) (mword_of_int 0x12000073 : mword 32)
    (mword_of_int (KernelSyms.kvminithart + 0x20) : mword 64) (SFENCE_VMA (zreg, zreg)) kd_12000073. Qed.

  Lemma kvi_24 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x24) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x24) (mword_of_int 0x60a2 : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x24) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_60a2 exec_execute_C_LDSP. Qed.

  Lemma kvi_26 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x26) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x26) (mword_of_int 0x6402 : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x26) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_6402 exec_execute_C_LDSP. Qed.

  Lemma kvi_28 : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x28) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x28) (mword_of_int 0x0141 : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x28) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_0141 exec_execute_C_ADDI. Qed.

  Lemma kvi_2a : kernel_text -∗ instr (mword_of_int (KernelSyms.kvminithart + 0x2a) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof using . mk_rvc (KernelSyms.kvminithart + 0x2a) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.kvminithart + 0x2a) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

End CodeKvminithart.
