(* CodeIlock.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's ilock: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [ili_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
From iris.program_logic Require Import language.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode00.
Require Import KernelDecode01.
Require Import KernelDecode02.
Require Import KernelDecode04.
Require Import KernelDecode05.
Require Import KernelDecode06.
Require Import KernelDecode07.
Require Import KernelDecode08.
Require Import KernelDecode09.
Require Import KernelDecode10.
Require Import KernelDecode11.
Require Import KernelDecode12.
Require Import KernelDecode13.
Require Import KernelDecode14.
Require Import KernelDecode15.
Require Import KernelDecode16.
Require Import KernelDecode17.
Require Import KernelDecode18.
Require Import KernelDecode19.
Require Import KernelDecode20.
Require Import KernelDecode21.
Require Import KernelDecode22.
Require Import KernelDecode23.
Require Import KernelDecode25.
Require Import KernelDecode26.
Require Import KernelDecode27.
Require Import KernelDecode28.
Require Import KernelDecode29.
Require Import KernelDecode30.
Require Import KernelDecode31.
Local Open Scope Z_scope.
Import Defs.


Section CodeIlock.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- ilock @ KernelSyms.ilock, 174 bytes ---- *)

  Lemma ili_00 : kernel_text -∗ instr (mword_of_int KernelSyms.ilock : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc KernelSyms.ilock (mword_of_int 0x1101 : mword 16)
    (mword_of_int KernelSyms.ilock : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1101 exec_execute_C_ADDI. Qed.

  Lemma ili_02 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x2) (mword_of_int 0xec06 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_ec06 exec_execute_C_SDSP. Qed.

  Lemma ili_04 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x4) (mword_of_int 0xe822 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e822 exec_execute_C_SDSP. Qed.

  Lemma ili_06 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x6) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x6) (mword_of_int 0xe426 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x6) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)) kd_e426 exec_execute_C_SDSP. Qed.

  Lemma ili_08 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x8) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x8) (mword_of_int 0x1000 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x8) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_1000 exec_execute_C_ADDI4SPN. Qed.

  Lemma ili_0a : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0xa) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 15 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 2)), BEQ)).
  Proof using . mk_rvc (KernelSyms.ilock + 0xa) (mword_of_int 0xcd19 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0xa) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 15 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 2)), BEQ)) kd_cd19 exec_execute_C_BEQZ. Qed.

  Lemma ili_0c : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0xc) : mword 64) true (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 9), ADD)).
  Proof using . mk_rvc (KernelSyms.ilock + 0xc) (mword_of_int 0x84aa : mword 16)
    (mword_of_int (KernelSyms.ilock + 0xc) : mword 64) (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 9), ADD)) kd_84aa exec_execute_C_MV. Qed.

  Lemma ili_0e : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0xe) : mword 64) true (LOAD (mword_of_int 8 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 15), false, 4)).
  Proof using . mk_rvc (KernelSyms.ilock + 0xe) (mword_of_int 0x451c : mword 16)
    (mword_of_int (KernelSyms.ilock + 0xe) : mword 64) (LOAD (mword_of_int 8 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 15), false, 4)) kd_451c ke_451c. Qed.

  Lemma ili_10 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x10) : mword 64) false (BTYPE (mword_of_int 24 : mword 13, Regidx (mword_of_int 15), zreg, BGE)).
  Proof using . mk_base (KernelSyms.ilock + 0x10) (mword_of_int 0x00f05c63 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x10) : mword 64) (BTYPE (mword_of_int 24 : mword 13, Regidx (mword_of_int 15), zreg, BGE)) kd_00f05c63. Qed.

  Lemma ili_14 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x14) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x14) (mword_of_int 0x0541 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x14) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_0541 exec_execute_C_ADDI. Qed.

  Lemma ili_16 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x16) : mword 64) false (JAL (mword_of_int 3440 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.ilock + 0x16) (mword_of_int 0x571000ef : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x16) : mword 64) (JAL (mword_of_int 3440 : mword 21, Regidx (mword_of_int 1))) kd_571000ef. Qed.

  Lemma ili_1a : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x1a) : mword 64) true (LOAD (mword_of_int 64 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x1a) (mword_of_int 0x40bc : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x1a) : mword 64) (LOAD (mword_of_int 64 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)) kd_40bc ke_40bc. Qed.

  Lemma ili_1c : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x1c) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 13 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 7)), BEQ)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x1c) (mword_of_int 0xcf89 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x1c) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 13 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 7)), BEQ)) kd_cf89 exec_execute_C_BEQZ. Qed.

  Lemma ili_1e : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x1e) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x1e) (mword_of_int 0x60e2 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x1e) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_60e2 exec_execute_C_LDSP. Qed.

  Lemma ili_20 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x20) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x20) (mword_of_int 0x6442 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x20) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_6442 exec_execute_C_LDSP. Qed.

  Lemma ili_22 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x22) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x22) (mword_of_int 0x64a2 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x22) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)) kd_64a2 exec_execute_C_LDSP. Qed.

  Lemma ili_24 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x24) : mword 64) true (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x24) (mword_of_int 0x6105 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x24) : mword 64) (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)) kd_6105 exec_execute_C_ADDI16SP. Qed.

  Lemma ili_26 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x26) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x26) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x26) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

  Lemma ili_28 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x28) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x28) (mword_of_int 0xe04a : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x28) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)) kd_e04a exec_execute_C_SDSP. Qed.

  Lemma ili_2a : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x2a) : mword 64) false (UTYPE (mword_of_int 4 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof using . mk_base (KernelSyms.ilock + 0x2a) (mword_of_int 0x00004517 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x2a) : mword 64) (UTYPE (mword_of_int 4 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00004517. Qed.

  Lemma ili_2e : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x2e) : mword 64) false (ITYPE (mword_of_int 264 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof using . mk_base (KernelSyms.ilock + 0x2e) (mword_of_int 0x10850513 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x2e) : mword 64) (ITYPE (mword_of_int 264 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_10850513. Qed.

  Lemma ili_32 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x32) : mword 64) false (JAL (mword_of_int 2086128 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.ilock + 0x32) (mword_of_int 0xcf0fd0ef : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x32) : mword 64) (JAL (mword_of_int 2086128 : mword 21, Regidx (mword_of_int 1))) kd_cf0fd0ef. Qed.

  Lemma ili_36 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x36) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x36) (mword_of_int 0xe04a : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x36) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)) kd_e04a exec_execute_C_SDSP. Qed.

  Lemma ili_38 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x38) : mword 64) true (LOAD (mword_of_int 4 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x38) (mword_of_int 0x40dc : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x38) : mword 64) (LOAD (mword_of_int 4 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)) kd_40dc ke_40dc. Qed.

  Lemma ili_3a : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x3a) : mword 64) false (SHIFTIWOP (mword_of_int 4 : mword 5, Regidx (mword_of_int 15), Regidx (mword_of_int 15), SRLIW)).
  Proof using . mk_base (KernelSyms.ilock + 0x3a) (mword_of_int 0x0047d79b : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x3a) : mword 64) (SHIFTIWOP (mword_of_int 4 : mword 5, Regidx (mword_of_int 15), Regidx (mword_of_int 15), SRLIW)) kd_0047d79b. Qed.

  Lemma ili_3e : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x3e) : mword 64) false (UTYPE (mword_of_int 30 : mword 20, Regidx (mword_of_int 11), AUIPC)).
  Proof using . mk_base (KernelSyms.ilock + 0x3e) (mword_of_int 0x0001e597 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x3e) : mword 64) (UTYPE (mword_of_int 30 : mword 20, Regidx (mword_of_int 11), AUIPC)) kd_0001e597. Qed.

  Lemma ili_42 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x42) : mword 64) false (LOAD (mword_of_int 2052 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 11), false, 4)).
  Proof using . mk_base (KernelSyms.ilock + 0x42) (mword_of_int 0x8045a583 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x42) : mword 64) (LOAD (mword_of_int 2052 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 11), false, 4)) kd_8045a583. Qed.

  Lemma ili_46 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x46) : mword 64) true (RTYPEW (creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 3)), creg2reg_idx (Cregidx (mword_of_int 3)), ADDW)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x46) (mword_of_int 0x9dbd : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x46) : mword 64) (RTYPEW (creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 3)), creg2reg_idx (Cregidx (mword_of_int 3)), ADDW)) kd_9dbd exec_execute_C_ADDW. Qed.

  Lemma ili_48 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x48) : mword 64) true (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 10), false, 4)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x48) (mword_of_int 0x4088 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x48) : mword 64) (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 10), false, 4)) kd_4088 ke_4088. Qed.

  Lemma ili_4a : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x4a) : mword 64) false (JAL (mword_of_int 2095390 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.ilock + 0x4a) (mword_of_int 0x91fff0ef : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x4a) : mword 64) (JAL (mword_of_int 2095390 : mword 21, Regidx (mword_of_int 1))) kd_91fff0ef. Qed.

  Lemma ili_4e : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x4e) : mword 64) true (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 18), ADD)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x4e) (mword_of_int 0x892a : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x4e) : mword 64) (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 18), ADD)) kd_892a exec_execute_C_MV. Qed.

  Lemma ili_50 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x50) : mword 64) false (ITYPE (mword_of_int 88 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 11), ADDI)).
  Proof using . mk_base (KernelSyms.ilock + 0x50) (mword_of_int 0x05850593 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x50) : mword 64) (ITYPE (mword_of_int 88 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 11), ADDI)) kd_05850593. Qed.

  Lemma ili_54 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x54) : mword 64) true (LOAD (mword_of_int 4 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x54) (mword_of_int 0x40dc : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x54) : mword 64) (LOAD (mword_of_int 4 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)) kd_40dc ke_40dc. Qed.

  Lemma ili_56 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x56) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 15 : mword 6), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), ANDI)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x56) (mword_of_int 0x8bbd : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x56) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 15 : mword 6), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), ANDI)) kd_8bbd ke_8bbd. Qed.

  Lemma ili_58 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x58) : mword 64) true (SHIFTIOP (mword_of_int 6 : mword 6, Regidx (mword_of_int 15), Regidx (mword_of_int 15), SLLI)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x58) (mword_of_int 0x079a : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x58) : mword 64) (SHIFTIOP (mword_of_int 6 : mword 6, Regidx (mword_of_int 15), Regidx (mword_of_int 15), SLLI)) kd_079a exec_execute_C_SLLI. Qed.

  Lemma ili_5a : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x5a) : mword 64) true (RTYPE (Regidx (mword_of_int 15), Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADD)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x5a) (mword_of_int 0x95be : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x5a) : mword 64) (RTYPE (Regidx (mword_of_int 15), Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADD)) kd_95be exec_execute_C_ADD. Qed.

  Lemma ili_5c : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x5c) : mword 64) false (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 2)).
  Proof using . mk_base (KernelSyms.ilock + 0x5c) (mword_of_int 0x00059783 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x5c) : mword 64) (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 2)) kd_00059783. Qed.

  Lemma ili_60 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x60) : mword 64) false (STORE (mword_of_int 68 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 2)).
  Proof using . mk_base (KernelSyms.ilock + 0x60) (mword_of_int 0x04f49223 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x60) : mword 64) (STORE (mword_of_int 68 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 2)) kd_04f49223. Qed.

  Lemma ili_64 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x64) : mword 64) false (LOAD (mword_of_int 2 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 2)).
  Proof using . mk_base (KernelSyms.ilock + 0x64) (mword_of_int 0x00259783 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x64) : mword 64) (LOAD (mword_of_int 2 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 2)) kd_00259783. Qed.

  Lemma ili_68 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x68) : mword 64) false (STORE (mword_of_int 70 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 2)).
  Proof using . mk_base (KernelSyms.ilock + 0x68) (mword_of_int 0x04f49323 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x68) : mword 64) (STORE (mword_of_int 70 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 2)) kd_04f49323. Qed.

  Lemma ili_6c : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x6c) : mword 64) false (LOAD (mword_of_int 4 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 2)).
  Proof using . mk_base (KernelSyms.ilock + 0x6c) (mword_of_int 0x00459783 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x6c) : mword 64) (LOAD (mword_of_int 4 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 2)) kd_00459783. Qed.

  Lemma ili_70 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x70) : mword 64) false (STORE (mword_of_int 72 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 2)).
  Proof using . mk_base (KernelSyms.ilock + 0x70) (mword_of_int 0x04f49423 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x70) : mword 64) (STORE (mword_of_int 72 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 2)) kd_04f49423. Qed.

  Lemma ili_74 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x74) : mword 64) false (LOAD (mword_of_int 6 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 2)).
  Proof using . mk_base (KernelSyms.ilock + 0x74) (mword_of_int 0x00659783 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x74) : mword 64) (LOAD (mword_of_int 6 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 2)) kd_00659783. Qed.

  Lemma ili_78 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x78) : mword 64) false (STORE (mword_of_int 74 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 2)).
  Proof using . mk_base (KernelSyms.ilock + 0x78) (mword_of_int 0x04f49523 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x78) : mword 64) (STORE (mword_of_int 74 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 2)) kd_04f49523. Qed.

  Lemma ili_7c : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x7c) : mword 64) true (LOAD (mword_of_int 8 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 4)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x7c) (mword_of_int 0x459c : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x7c) : mword 64) (LOAD (mword_of_int 8 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 4)) kd_459c ke_459c. Qed.

  Lemma ili_7e : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x7e) : mword 64) true (STORE (mword_of_int 76 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x7e) (mword_of_int 0xc4fc : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x7e) : mword 64) (STORE (mword_of_int 76 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)) kd_c4fc ke_c4fc. Qed.

  Lemma ili_80 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x80) : mword 64) false (ITYPE (mword_of_int 52 : mword 12, zreg, Regidx (mword_of_int 12), ADDI)).
  Proof using . mk_base (KernelSyms.ilock + 0x80) (mword_of_int 0x03400613 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x80) : mword 64) (ITYPE (mword_of_int 52 : mword 12, zreg, Regidx (mword_of_int 12), ADDI)) kd_03400613. Qed.

  Lemma ili_84 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x84) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 12 : mword 6), Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADDI)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x84) (mword_of_int 0x05b1 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x84) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 12 : mword 6), Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADDI)) kd_05b1 exec_execute_C_ADDI. Qed.

  Lemma ili_86 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x86) : mword 64) false (ITYPE (mword_of_int 80 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 10), ADDI)).
  Proof using . mk_base (KernelSyms.ilock + 0x86) (mword_of_int 0x05048513 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x86) : mword 64) (ITYPE (mword_of_int 80 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 10), ADDI)) kd_05048513. Qed.

  Lemma ili_8a : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x8a) : mword 64) false (JAL (mword_of_int 2087344 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.ilock + 0x8a) (mword_of_int 0x9b1fd0ef : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x8a) : mword 64) (JAL (mword_of_int 2087344 : mword 21, Regidx (mword_of_int 1))) kd_9b1fd0ef. Qed.

  Lemma ili_8e : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x8e) : mword 64) true (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 10), ADD)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x8e) (mword_of_int 0x854a : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x8e) : mword 64) (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 10), ADD)) kd_854a exec_execute_C_MV. Qed.

  Lemma ili_90 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x90) : mword 64) false (JAL (mword_of_int 2095584 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.ilock + 0x90) (mword_of_int 0x9e1ff0ef : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x90) : mword 64) (JAL (mword_of_int 2095584 : mword 21, Regidx (mword_of_int 1))) kd_9e1ff0ef. Qed.

  Lemma ili_94 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x94) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x94) (mword_of_int 0x4785 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x94) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), zreg, Regidx (mword_of_int 15), ADDI)) kd_4785 exec_execute_C_LI. Qed.

  Lemma ili_96 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x96) : mword 64) true (STORE (mword_of_int 64 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x96) (mword_of_int 0xc0bc : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x96) : mword 64) (STORE (mword_of_int 64 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)) kd_c0bc ke_c0bc. Qed.

  Lemma ili_98 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x98) : mword 64) false (LOAD (mword_of_int 68 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 2)).
  Proof using . mk_base (KernelSyms.ilock + 0x98) (mword_of_int 0x04449783 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0x98) : mword 64) (LOAD (mword_of_int 68 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 2)) kd_04449783. Qed.

  Lemma ili_9c : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x9c) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 3 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 7)), BEQ)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x9c) (mword_of_int 0xc399 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x9c) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 3 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 7)), BEQ)) kd_c399 exec_execute_C_BEQZ. Qed.

  Lemma ili_9e : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0x9e) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)).
  Proof using . mk_rvc (KernelSyms.ilock + 0x9e) (mword_of_int 0x6902 : mword 16)
    (mword_of_int (KernelSyms.ilock + 0x9e) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)) kd_6902 exec_execute_C_LDSP. Qed.

  Lemma ili_a0 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0xa0) : mword 64) true (JAL (sign_extend' 21 (concat_vec (mword_of_int 1983 : mword 11) ('b"0")), zreg)).
  Proof using . mk_rvc (KernelSyms.ilock + 0xa0) (mword_of_int 0xbfbd : mword 16)
    (mword_of_int (KernelSyms.ilock + 0xa0) : mword 64) (JAL (sign_extend' 21 (concat_vec (mword_of_int 1983 : mword 11) ('b"0")), zreg)) kd_bfbd exec_execute_C_J. Qed.

  Lemma ili_a2 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0xa2) : mword 64) false (UTYPE (mword_of_int 4 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof using . mk_base (KernelSyms.ilock + 0xa2) (mword_of_int 0x00004517 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0xa2) : mword 64) (UTYPE (mword_of_int 4 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00004517. Qed.

  Lemma ili_a6 : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0xa6) : mword 64) false (ITYPE (mword_of_int 152 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof using . mk_base (KernelSyms.ilock + 0xa6) (mword_of_int 0x09850513 : mword 32)
    (mword_of_int (KernelSyms.ilock + 0xa6) : mword 64) (ITYPE (mword_of_int 152 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_09850513. Qed.

  Lemma ili_aa : kernel_text -∗ instr (mword_of_int (KernelSyms.ilock + 0xaa) : mword 64) false (JAL (mword_of_int 2085968 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.ilock + 0xaa) (mword_of_int 0xc50fd0ef : mword 32)
    (mword_of_int (KernelSyms.ilock + 0xaa) : mword 64) (JAL (mword_of_int 2085968 : mword 21, Regidx (mword_of_int 1))) kd_c50fd0ef. Qed.

End CodeIlock.
