(* CodeBrelse.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's brelse: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [bri_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
From iris.program_logic Require Import language.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode02.
Require Import KernelDecode03.
Require Import KernelDecode04.
Require Import KernelDecode05.
Require Import KernelDecode07.
Require Import KernelDecode10.
Require Import KernelDecode12.
Require Import KernelDecode13.
Require Import KernelDecode14.
Require Import KernelDecode15.
Require Import KernelDecode16.
Require Import KernelDecode17.
Require Import KernelDecode18.
Require Import KernelDecode19.
Require Import KernelDecode20.
Require Import KernelDecode21.
Require Import KernelDecode22.
Require Import KernelDecode23.
Require Import KernelDecode24.
Require Import KernelDecode25.
Require Import KernelDecode26.
Require Import KernelDecode27.
Require Import KernelDecode28.
Require Import KernelDecode29.
Local Open Scope Z_scope.
Import Defs.


Section CodeBrelse.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- brelse @ KernelSyms.brelse, 132 bytes ---- *)

  Lemma bri_00 : kernel_text -∗ instr (mword_of_int KernelSyms.brelse : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc KernelSyms.brelse (mword_of_int 0x1101 : mword 16)
    (mword_of_int KernelSyms.brelse : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 32 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1101 exec_execute_C_ADDI. Qed.

  Lemma bri_02 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x2) (mword_of_int 0xec06 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_ec06 exec_execute_C_SDSP. Qed.

  Lemma bri_04 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x4) (mword_of_int 0xe822 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e822 exec_execute_C_SDSP. Qed.

  Lemma bri_06 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x6) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x6) (mword_of_int 0xe426 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x6) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 9), sp, 8)) kd_e426 exec_execute_C_SDSP. Qed.

  Lemma bri_08 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x8) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x8) (mword_of_int 0xe04a : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x8) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 18), sp, 8)) kd_e04a exec_execute_C_SDSP. Qed.

  Lemma bri_0a : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0xa) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof using . mk_rvc (KernelSyms.brelse + 0xa) (mword_of_int 0x1000 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0xa) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 8 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_1000 exec_execute_C_ADDI4SPN. Qed.

  Lemma bri_0c : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0xc) : mword 64) true (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 9), ADD)).
  Proof using . mk_rvc (KernelSyms.brelse + 0xc) (mword_of_int 0x84aa : mword 16)
    (mword_of_int (KernelSyms.brelse + 0xc) : mword 64) (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 9), ADD)) kd_84aa exec_execute_C_MV. Qed.

  Lemma bri_0e : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0xe) : mword 64) false (ITYPE (mword_of_int 16 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 18), ADDI)).
  Proof using . mk_base (KernelSyms.brelse + 0xe) (mword_of_int 0x01050913 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0xe) : mword 64) (ITYPE (mword_of_int 16 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 18), ADDI)) kd_01050913. Qed.

  Lemma bri_12 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x12) : mword 64) true (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 10), ADD)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x12) (mword_of_int 0x854a : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x12) : mword 64) (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 10), ADD)) kd_854a exec_execute_C_MV. Qed.

  Lemma bri_14 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x14) : mword 64) false (JAL (mword_of_int 5006 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.brelse + 0x14) (mword_of_int 0x38e010ef : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x14) : mword 64) (JAL (mword_of_int 5006 : mword 21, Regidx (mword_of_int 1))) kd_38e010ef. Qed.

  Lemma bri_18 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x18) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 48 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 2)), BEQ)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x18) (mword_of_int 0xc125 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x18) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 48 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 2)), BEQ)) kd_c125 exec_execute_C_BEQZ. Qed.

  Lemma bri_1a : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x1a) : mword 64) true (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 10), ADD)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x1a) (mword_of_int 0x854a : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x1a) : mword 64) (RTYPE (Regidx (mword_of_int 18), zreg, Regidx (mword_of_int 10), ADD)) kd_854a exec_execute_C_MV. Qed.

  Lemma bri_1c : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x1c) : mword 64) false (JAL (mword_of_int 4942 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.brelse + 0x1c) (mword_of_int 0x34e010ef : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x1c) : mword 64) (JAL (mword_of_int 4942 : mword 21, Regidx (mword_of_int 1))) kd_34e010ef. Qed.

  Lemma bri_20 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x20) : mword 64) false (UTYPE (mword_of_int 21 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof using . mk_base (KernelSyms.brelse + 0x20) (mword_of_int 0x00015517 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x20) : mword 64) (UTYPE (mword_of_int 21 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00015517. Qed.

  Lemma bri_24 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x24) : mword 64) false (ITYPE (mword_of_int 1754 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof using . mk_base (KernelSyms.brelse + 0x24) (mword_of_int 0x6da50513 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x24) : mword 64) (ITYPE (mword_of_int 1754 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_6da50513. Qed.

  Lemma bri_28 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x28) : mword 64) false (JAL (mword_of_int 2088578 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.brelse + 0x28) (mword_of_int 0xe83fd0ef : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x28) : mword 64) (JAL (mword_of_int 2088578 : mword 21, Regidx (mword_of_int 1))) kd_e83fd0ef. Qed.

  Lemma bri_2c : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x2c) : mword 64) true (LOAD (mword_of_int 64 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x2c) (mword_of_int 0x40bc : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x2c) : mword 64) (LOAD (mword_of_int 64 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 4)) kd_40bc ke_40bc. Qed.

  Lemma bri_2e : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x2e) : mword 64) true (ADDIW (sign_extend' 12 (mword_of_int 63 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15))).
  Proof using . mk_rvc (KernelSyms.brelse + 0x2e) (mword_of_int 0x37fd : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x2e) : mword 64) (ADDIW (sign_extend' 12 (mword_of_int 63 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15))) kd_37fd exec_execute_C_ADDIW. Qed.

  Lemma bri_30 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x30) : mword 64) true (STORE (mword_of_int 64 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x30) (mword_of_int 0xc0bc : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x30) : mword 64) (STORE (mword_of_int 64 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 4)) kd_c0bc ke_c0bc. Qed.

  Lemma bri_32 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x32) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 23 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 7)), BNE)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x32) (mword_of_int 0xe79d : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x32) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 23 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 7)), BNE)) kd_e79d exec_execute_C_BNEZ. Qed.

  Lemma bri_34 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x34) : mword 64) true (LOAD (mword_of_int 80 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), false, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x34) (mword_of_int 0x68b8 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x34) : mword 64) (LOAD (mword_of_int 80 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), false, 8)) kd_68b8 ke_68b8. Qed.

  Lemma bri_36 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x36) : mword 64) true (LOAD (mword_of_int 72 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x36) (mword_of_int 0x64bc : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x36) : mword 64) (LOAD (mword_of_int 72 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 8)) kd_64bc ke_64bc. Qed.

  Lemma bri_38 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x38) : mword 64) true (STORE (mword_of_int 72 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x38) (mword_of_int 0xe73c : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x38) : mword 64) (STORE (mword_of_int 72 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 8)) kd_e73c ke_e73c. Qed.

  Lemma bri_3a : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x3a) : mword 64) true (LOAD (mword_of_int 80 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), false, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x3a) (mword_of_int 0x68b8 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x3a) : mword 64) (LOAD (mword_of_int 80 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), false, 8)) kd_68b8 ke_68b8. Qed.

  Lemma bri_3c : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x3c) : mword 64) true (STORE (mword_of_int 80 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x3c) (mword_of_int 0xebb8 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x3c) : mword 64) (STORE (mword_of_int 80 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 8)) kd_ebb8 ke_ebb8. Qed.

  Lemma bri_3e : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x3e) : mword 64) false (UTYPE (mword_of_int 29 : mword 20, Regidx (mword_of_int 15), AUIPC)).
  Proof using . mk_base (KernelSyms.brelse + 0x3e) (mword_of_int 0x0001d797 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x3e) : mword 64) (UTYPE (mword_of_int 29 : mword 20, Regidx (mword_of_int 15), AUIPC)) kd_0001d797. Qed.

  Lemma bri_42 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x42) : mword 64) false (ITYPE (mword_of_int 1724 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)).
  Proof using . mk_base (KernelSyms.brelse + 0x42) (mword_of_int 0x6bc78793 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x42) : mword 64) (ITYPE (mword_of_int 1724 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)) kd_6bc78793. Qed.

  Lemma bri_46 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x46) : mword 64) false (LOAD (mword_of_int 696 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), false, 8)).
  Proof using . mk_base (KernelSyms.brelse + 0x46) (mword_of_int 0x2b87b703 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x46) : mword 64) (LOAD (mword_of_int 696 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), false, 8)) kd_2b87b703. Qed.

  Lemma bri_4a : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x4a) : mword 64) true (STORE (mword_of_int 80 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 9), 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x4a) (mword_of_int 0xe8b8 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x4a) : mword 64) (STORE (mword_of_int 80 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 9), 8)) kd_e8b8 ke_e8b8. Qed.

  Lemma bri_4c : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x4c) : mword 64) false (UTYPE (mword_of_int 30 : mword 20, Regidx (mword_of_int 14), AUIPC)).
  Proof using . mk_base (KernelSyms.brelse + 0x4c) (mword_of_int 0x0001e717 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x4c) : mword 64) (UTYPE (mword_of_int 30 : mword 20, Regidx (mword_of_int 14), AUIPC)) kd_0001e717. Qed.

  Lemma bri_50 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x50) : mword 64) false (ITYPE (mword_of_int 2326 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)).
  Proof using . mk_base (KernelSyms.brelse + 0x50) (mword_of_int 0x91670713 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x50) : mword 64) (ITYPE (mword_of_int 2326 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 14), ADDI)) kd_91670713. Qed.

  Lemma bri_54 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x54) : mword 64) true (STORE (mword_of_int 72 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 9), 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x54) (mword_of_int 0xe4b8 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x54) : mword 64) (STORE (mword_of_int 72 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 9), 8)) kd_e4b8 ke_e4b8. Qed.

  Lemma bri_56 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x56) : mword 64) false (LOAD (mword_of_int 696 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), false, 8)).
  Proof using . mk_base (KernelSyms.brelse + 0x56) (mword_of_int 0x2b87b703 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x56) : mword 64) (LOAD (mword_of_int 696 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), false, 8)) kd_2b87b703. Qed.

  Lemma bri_5a : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x5a) : mword 64) true (STORE (mword_of_int 72 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x5a) (mword_of_int 0xe724 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x5a) : mword 64) (STORE (mword_of_int 72 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), 8)) kd_e724 ke_e724. Qed.

  Lemma bri_5c : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x5c) : mword 64) false (STORE (mword_of_int 696 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), 8)).
  Proof using . mk_base (KernelSyms.brelse + 0x5c) (mword_of_int 0x2a97bc23 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x5c) : mword 64) (STORE (mword_of_int 696 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), 8)) kd_2a97bc23. Qed.

  Lemma bri_60 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x60) : mword 64) false (UTYPE (mword_of_int 21 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof using . mk_base (KernelSyms.brelse + 0x60) (mword_of_int 0x00015517 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x60) : mword 64) (UTYPE (mword_of_int 21 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00015517. Qed.

  Lemma bri_64 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x64) : mword 64) false (ITYPE (mword_of_int 1690 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof using . mk_base (KernelSyms.brelse + 0x64) (mword_of_int 0x69a50513 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x64) : mword 64) (ITYPE (mword_of_int 1690 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_69a50513. Qed.

  Lemma bri_68 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x68) : mword 64) false (JAL (mword_of_int 2088650 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.brelse + 0x68) (mword_of_int 0xecbfd0ef : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x68) : mword 64) (JAL (mword_of_int 2088650 : mword 21, Regidx (mword_of_int 1))) kd_ecbfd0ef. Qed.

  Lemma bri_6c : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x6c) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x6c) (mword_of_int 0x60e2 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x6c) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 3 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_60e2 exec_execute_C_LDSP. Qed.

  Lemma bri_6e : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x6e) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x6e) (mword_of_int 0x6442 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x6e) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 2 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_6442 exec_execute_C_LDSP. Qed.

  Lemma bri_70 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x70) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x70) (mword_of_int 0x64a2 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x70) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 9), false, 8)) kd_64a2 exec_execute_C_LDSP. Qed.

  Lemma bri_72 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x72) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x72) (mword_of_int 0x6902 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x72) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 18), false, 8)) kd_6902 exec_execute_C_LDSP. Qed.

  Lemma bri_74 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x74) : mword 64) true (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x74) (mword_of_int 0x6105 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x74) : mword 64) (ITYPE (caddi16sp_imm (mword_of_int 2 : mword 6), sp, sp, ADDI)) kd_6105 exec_execute_C_ADDI16SP. Qed.

  Lemma bri_76 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x76) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof using . mk_rvc (KernelSyms.brelse + 0x76) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.brelse + 0x76) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

  Lemma bri_78 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x78) : mword 64) false (UTYPE (mword_of_int 4 : mword 20, Regidx (mword_of_int 10), AUIPC)).
  Proof using . mk_base (KernelSyms.brelse + 0x78) (mword_of_int 0x00004517 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x78) : mword 64) (UTYPE (mword_of_int 4 : mword 20, Regidx (mword_of_int 10), AUIPC)) kd_00004517. Qed.

  Lemma bri_7c : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x7c) : mword 64) false (ITYPE (mword_of_int 1474 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)).
  Proof using . mk_base (KernelSyms.brelse + 0x7c) (mword_of_int 0x5c250513 : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x7c) : mword 64) (ITYPE (mword_of_int 1474 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI)) kd_5c250513. Qed.

  Lemma bri_80 : kernel_text -∗ instr (mword_of_int (KernelSyms.brelse + 0x80) : mword 64) false (JAL (mword_of_int 2087474 : mword 21, Regidx (mword_of_int 1))).
  Proof using . mk_base (KernelSyms.brelse + 0x80) (mword_of_int 0xa33fd0ef : mword 32)
    (mword_of_int (KernelSyms.brelse + 0x80) : mword 64) (JAL (mword_of_int 2087474 : mword 21, Regidx (mword_of_int 1))) kd_a33fd0ef. Qed.

End CodeBrelse.
