(* CodeMemset.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for xv6's memset: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [minstr_<off>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
From iris.program_logic Require Import language.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvPtsto.
Require Import InstrBytes.
Require Import KernelText.
Require Import WpMmodeLeafBase.
From Kernel Require KernelInstrs.
From Kernel Require KernelSyms.
Require Import KernelDecode01.
Require Import KernelDecode04.
Require Import KernelDecode06.
Require Import KernelDecode07.
Require Import KernelDecode08.
Require Import KernelDecode11.
Require Import KernelDecode13.
Require Import KernelDecode14.
Require Import KernelDecode15.
Require Import KernelDecode16.
Require Import KernelDecode21.
Require Import KernelDecode24.
Require Import KernelDecode26.
Require Import KernelDecode29.
Require Import KernelDecode31.
Local Open Scope Z_scope.
Import Defs.


Section CodeMemset.
  Context `{!riscvGS Σ}.
  Context `{GEN : GenId} `{CID : CpuId}.

  (* ---- memset @ KernelSyms.memset, 38 bytes ---- *)

  Lemma minstr_000 : kernel_text -∗ instr (mword_of_int KernelSyms.memset : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc KernelSyms.memset (mword_of_int 0x1141 : mword 16)
    (mword_of_int KernelSyms.memset : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 48 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_1141 exec_execute_C_ADDI. Qed.

  Lemma minstr_002 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x2) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)).
  Proof using . mk_rvc (KernelSyms.memset + 0x2) (mword_of_int 0xe406 : mword 16)
    (mword_of_int (KernelSyms.memset + 0x2) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), Regidx (mword_of_int 1), sp, 8)) kd_e406 exec_execute_C_SDSP. Qed.

  Lemma minstr_004 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x4) : mword 64) true (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)).
  Proof using . mk_rvc (KernelSyms.memset + 0x4) (mword_of_int 0xe022 : mword 16)
    (mword_of_int (KernelSyms.memset + 0x4) : mword 64) (STORE (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), Regidx (mword_of_int 8), sp, 8)) kd_e022 exec_execute_C_SDSP. Qed.

  Lemma minstr_006 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x6) : mword 64) true (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)).
  Proof using . mk_rvc (KernelSyms.memset + 0x6) (mword_of_int 0x0800 : mword 16)
    (mword_of_int (KernelSyms.memset + 0x6) : mword 64) (ITYPE (caddi4spn_imm (mword_of_int 4 : mword 8), sp, creg2reg_idx (Cregidx (mword_of_int 0)), ADDI)) kd_0800 exec_execute_C_ADDI4SPN. Qed.

  Lemma minstr_008 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x8) : mword 64) true (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 11 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 4)), BEQ)).
  Proof using . mk_rvc (KernelSyms.memset + 0x8) (mword_of_int 0xca19 : mword 16)
    (mword_of_int (KernelSyms.memset + 0x8) : mword 64) (BTYPE (sign_extend' 13 (concat_vec (mword_of_int 11 : mword 8) ('b"0")), zreg, creg2reg_idx (Cregidx (mword_of_int 4)), BEQ)) kd_ca19 exec_execute_C_BEQZ. Qed.

  Lemma minstr_00a : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0xa) : mword 64) true (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 15), ADD)).
  Proof using . mk_rvc (KernelSyms.memset + 0xa) (mword_of_int 0x87aa : mword 16)
    (mword_of_int (KernelSyms.memset + 0xa) : mword 64) (RTYPE (Regidx (mword_of_int 10), zreg, Regidx (mword_of_int 15), ADD)) kd_87aa exec_execute_C_MV. Qed.

  Lemma minstr_00c : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0xc) : mword 64) true (SHIFTIOP (mword_of_int 32 : mword 6, Regidx (mword_of_int 12), Regidx (mword_of_int 12), SLLI)).
  Proof using . mk_rvc (KernelSyms.memset + 0xc) (mword_of_int 0x1602 : mword 16)
    (mword_of_int (KernelSyms.memset + 0xc) : mword 64) (SHIFTIOP (mword_of_int 32 : mword 6, Regidx (mword_of_int 12), Regidx (mword_of_int 12), SLLI)) kd_1602 exec_execute_C_SLLI. Qed.

  Lemma minstr_00e : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0xe) : mword 64) true (SHIFTIOP (mword_of_int 32 : mword 6, creg2reg_idx (Cregidx (mword_of_int 4)), creg2reg_idx (Cregidx (mword_of_int 4)), SRLI)).
  Proof using . mk_rvc (KernelSyms.memset + 0xe) (mword_of_int 0x9201 : mword 16)
    (mword_of_int (KernelSyms.memset + 0xe) : mword 64) (SHIFTIOP (mword_of_int 32 : mword 6, creg2reg_idx (Cregidx (mword_of_int 4)), creg2reg_idx (Cregidx (mword_of_int 4)), SRLI)) kd_9201 exec_execute_C_SRLI. Qed.

  Lemma minstr_010 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x10) : mword 64) false (RTYPE (Regidx (mword_of_int 10), Regidx (mword_of_int 12), Regidx (mword_of_int 14), ADD)).
  Proof using . mk_base (KernelSyms.memset + 0x10) (mword_of_int 0x00a60733 : mword 32)
    (mword_of_int (KernelSyms.memset + 0x10) : mword 64) (RTYPE (Regidx (mword_of_int 10), Regidx (mword_of_int 12), Regidx (mword_of_int 14), ADD)) kd_00a60733. Qed.

  Lemma minstr_014 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x14) : mword 64) false (STORE (mword_of_int 0 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), 1)).
  Proof using . mk_base (KernelSyms.memset + 0x14) (mword_of_int 0x00b78023 : mword 32)
    (mword_of_int (KernelSyms.memset + 0x14) : mword 64) (STORE (mword_of_int 0 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), 1)) kd_00b78023. Qed.

  Lemma minstr_018 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x18) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)).
  Proof using . mk_rvc (KernelSyms.memset + 0x18) (mword_of_int 0x0785 : mword 16)
    (mword_of_int (KernelSyms.memset + 0x18) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 1 : mword 6), Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI)) kd_0785 exec_execute_C_ADDI. Qed.

  Lemma minstr_01a : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x1a) : mword 64) false (BTYPE (mword_of_int 8186 : mword 13, Regidx (mword_of_int 14), Regidx (mword_of_int 15), BNE)).
  Proof using . mk_base (KernelSyms.memset + 0x1a) (mword_of_int 0xfee79de3 : mword 32)
    (mword_of_int (KernelSyms.memset + 0x1a) : mword 64) (BTYPE (mword_of_int 8186 : mword 13, Regidx (mword_of_int 14), Regidx (mword_of_int 15), BNE)) kd_fee79de3. Qed.

  Lemma minstr_01e : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x1e) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)).
  Proof using . mk_rvc (KernelSyms.memset + 0x1e) (mword_of_int 0x60a2 : mword 16)
    (mword_of_int (KernelSyms.memset + 0x1e) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 1 : mword 6) ('b"000")), sp, Regidx (mword_of_int 1), false, 8)) kd_60a2 exec_execute_C_LDSP. Qed.

  Lemma minstr_020 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x20) : mword 64) true (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)).
  Proof using . mk_rvc (KernelSyms.memset + 0x20) (mword_of_int 0x6402 : mword 16)
    (mword_of_int (KernelSyms.memset + 0x20) : mword 64) (LOAD (zero_extend' 12 (concat_vec (mword_of_int 0 : mword 6) ('b"000")), sp, Regidx (mword_of_int 8), false, 8)) kd_6402 exec_execute_C_LDSP. Qed.

  Lemma minstr_022 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x22) : mword 64) true (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)).
  Proof using . mk_rvc (KernelSyms.memset + 0x22) (mword_of_int 0x0141 : mword 16)
    (mword_of_int (KernelSyms.memset + 0x22) : mword 64) (ITYPE (sign_extend' 12 (mword_of_int 16 : mword 6), Regidx (mword_of_int 2), Regidx (mword_of_int 2), ADDI)) kd_0141 exec_execute_C_ADDI. Qed.

  Lemma minstr_024 : kernel_text -∗ instr (mword_of_int (KernelSyms.memset + 0x24) : mword 64) true (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)).
  Proof using . mk_rvc (KernelSyms.memset + 0x24) (mword_of_int 0x8082 : mword 16)
    (mword_of_int (KernelSyms.memset + 0x24) : mword 64) (JALR (zeros' 12, Regidx (mword_of_int 1), zreg)) kd_8082 exec_execute_C_JR. Qed.

End CodeMemset.
