(* KernelDecode00.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for shard 0 of 32 of the kernel image's instruction words: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [kd_<word> / ke_<word>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
From iris.program_logic Require Import language.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvExec RiscvFetchExec.
Require Import WpMmodeLeafBase.
Require Import WpDecodeBridge.
Require Import WpRvcBridge.
Local Open Scope Z_scope.
Import Defs.

Lemma kd_078e s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x078e : mword 16)) s
  = Some (C_SLLI (mword_of_int 3, Regidx (mword_of_int 15)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_1880 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x1880 : mword 16)) s
  = Some (C_ADDI4SPN (Cregidx (mword_of_int 0), mword_of_int 28), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_367d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x367d : mword 16)) s
  = Some (C_ADDIW (mword_of_int 63, Regidx (mword_of_int 12)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_00003797 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00003797 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 3 : mword 20, Regidx (mword_of_int 15), AUIPC), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_4595 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4595 : mword 16)) s
  = Some (C_LI (mword_of_int 5, Regidx (mword_of_int 11)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_47b5 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x47b5 : mword 16)) s
  = Some (C_LI (mword_of_int 13, Regidx (mword_of_int 15)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_588c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x588c : mword 16)) s
  = Some (C_LW (mword_of_int 12, Cregidx (mword_of_int 1), Cregidx (mword_of_int 3)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_588c s :
  exec (execute (C_LW (mword_of_int 12, Cregidx (mword_of_int 1), Cregidx (mword_of_int 3)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 48 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 11), false, 4)), s).
Proof using . apply exec_execute_C_LW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_5d3c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x5d3c : mword 16)) s
  = Some (C_LW (mword_of_int 30, Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_5d3c s :
  exec (execute (C_LW (mword_of_int 30, Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 120 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 15), false, 4)), s).
Proof using . apply exec_execute_C_LW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_5d7c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x5d7c : mword 16)) s
  = Some (C_LW (mword_of_int 31, Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_5d7c s :
  exec (execute (C_LW (mword_of_int 31, Cregidx (mword_of_int 2), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 124 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 15), false, 4)), s).
Proof using . apply exec_execute_C_LW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_60bc s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x60bc : mword 16)) s
  = Some (C_LD (mword_of_int 8, Cregidx (mword_of_int 1), Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_60bc s :
  exec (execute (C_LD (mword_of_int 8, Cregidx (mword_of_int 1), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 64 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 15), false, 8)), s).
Proof using . apply exec_execute_C_LD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_6ba2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x6ba2 : mword 16)) s
  = Some (C_LDSP (mword_of_int 1, Regidx (mword_of_int 23)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_715d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x715d : mword 16)) s
  = Some (C_ADDI16SP (mword_of_int 59), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_7b9c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7b9c : mword 16)) s
  = Some (C_LD (mword_of_int 6, Cregidx (mword_of_int 7), Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_7b9c s :
  exec (execute (C_LD (mword_of_int 6, Cregidx (mword_of_int 7), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 48 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), false, 8)), s).
Proof using . apply exec_execute_C_LD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_7ca2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7ca2 : mword 16)) s
  = Some (C_LDSP (mword_of_int 5, Regidx (mword_of_int 25)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_85b2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x85b2 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 11), Regidx (mword_of_int 12)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_86ca s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x86ca : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 13), Regidx (mword_of_int 18)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_872a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x872a : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 14), Regidx (mword_of_int 10)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_8732 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8732 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 14), Regidx (mword_of_int 12)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_8ab6 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8ab6 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 21), Regidx (mword_of_int 13)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_8baa s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8baa : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 23), Regidx (mword_of_int 10)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_94be s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x94be : mword 16)) s
  = Some (C_ADD (Regidx (mword_of_int 9), Regidx (mword_of_int 15)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_995a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x995a : mword 16)) s
  = Some (C_ADD (Regidx (mword_of_int 18), Regidx (mword_of_int 22)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_9dbd s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x9dbd : mword 16)) s
  = Some (C_ADDW (Cregidx (mword_of_int 3), Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_a899 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xa899 : mword 16)) s
  = Some (C_J (mword_of_int 43), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_b535 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xb535 : mword 16)) s
  = Some (C_J (mword_of_int 1814), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_b7c9 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xb7c9 : mword 16)) s
  = Some (C_J (mword_of_int 2017), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_bdf5 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xbdf5 : mword 16)) s
  = Some (C_J (mword_of_int 1918), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_bf75 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xbf75 : mword 16)) s
  = Some (C_J (mword_of_int 2014), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_bf95 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xbf95 : mword 16)) s
  = Some (C_J (mword_of_int 1978), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_cd35 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xcd35 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 62, Cregidx (mword_of_int 2)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_e781 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xe781 : mword 16)) s
  = Some (C_BNEZ (mword_of_int 4, Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_e85a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xe85a : mword 16)) s
  = Some (C_SDSP (mword_of_int 2, Regidx (mword_of_int 22)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_e8a8 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xe8a8 : mword 16)) s
  = Some (C_SD (mword_of_int 10, Cregidx (mword_of_int 1), Cregidx (mword_of_int 2)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_e8a8 s :
  exec (execute (C_SD (mword_of_int 10, Cregidx (mword_of_int 1), Cregidx (mword_of_int 2)))) s
  = Some (ExecuteAs (STORE (mword_of_int 80 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 9), 8)), s).
Proof using . apply exec_execute_C_SD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_e925 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xe925 : mword 16)) s
  = Some (C_BNEZ (mword_of_int 56, Cregidx (mword_of_int 2)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_ef5e s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xef5e : mword 16)) s
  = Some (C_SDSP (mword_of_int 51, Regidx (mword_of_int 23)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_f606 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf606 : mword 16)) s
  = Some (C_SDSP (mword_of_int 37, Regidx (mword_of_int 1)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_f679 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf679 : mword 16)) s
  = Some (C_BNEZ (mword_of_int 231, Cregidx (mword_of_int 4)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_f756 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf756 : mword 16)) s
  = Some (C_SDSP (mword_of_int 53, Regidx (mword_of_int 21)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_ffce s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xffce : mword 16)) s
  = Some (C_SDSP (mword_of_int 63, Regidx (mword_of_int 19)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_00011717 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00011717 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 17 : mword 20, Regidx (mword_of_int 14), AUIPC), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00052223 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00052223 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 4 : mword 12, zreg, Regidx (mword_of_int 10), 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00054503 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00054503 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), true, 1), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00092703 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00092703 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 18), Regidx (mword_of_int 14), false, 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00098f63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00098f63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 30 : mword 13, zreg, Regidx (mword_of_int 19), BEQ), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_000b0563 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x000b0563 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 10 : mword 13, zreg, Regidx (mword_of_int 22), BEQ), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0015071b s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0015071b : mword 32) : M instruction) s
  = Some (ADDIW (mword_of_int 1 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 14)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_002a049b s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x002a049b : mword 32) : M instruction) s
  = Some (ADDIW (mword_of_int 2 : mword 12, Regidx (mword_of_int 20), Regidx (mword_of_int 9)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00495593 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00495593 : mword 32) : M instruction) s
  = Some (SHIFTIOP (mword_of_int 4 : mword 6, Regidx (mword_of_int 18), Regidx (mword_of_int 11), SRLI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0049a603 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0049a603 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 4 : mword 12, Regidx (mword_of_int 19), Regidx (mword_of_int 12), false, 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00840793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00840793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 8 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 15), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00a9b023 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00a9b023 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 0 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 19), 8), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00b81623 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00b81623 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 12 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 16), 2), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00e79223 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00e79223 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 4 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 2), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00e79323 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00e79323 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 6 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 2), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00f76863 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00f76863 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 16 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BLTU), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00f9f713 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00f9f713 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 15 : mword 12, Regidx (mword_of_int 19), Regidx (mword_of_int 14), ANDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0154ac23 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0154ac23 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 21), Regidx (mword_of_int 9), 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_015906b3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x015906b3 : mword 32) : M instruction) s
  = Some (RTYPE (Regidx (mword_of_int 21), Regidx (mword_of_int 18), Regidx (mword_of_int 13), ADD), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0187c783 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0187c783 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 24 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), true, 1), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_02000737 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02000737 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 8192 : mword 20, Regidx (mword_of_int 14), LUI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0207c363 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0207c363 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 38 : mword 13, zreg, Regidx (mword_of_int 15), BLT), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_02451783 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02451783 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 36 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 15), false, 2), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0297e863 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0297e863 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 48 : mword 13, Regidx (mword_of_int 9), Regidx (mword_of_int 15), BLTU), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_02d00793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02d00793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 45 : mword 12, zreg, Regidx (mword_of_int 15), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_02f4fe63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02f4fe63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 60 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 9), BGEU), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_03143c23 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x03143c23 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 56 : mword 12, Regidx (mword_of_int 17), Regidx (mword_of_int 8), 8), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_03451793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x03451793 : mword 32) : M instruction) s
  = Some (SHIFTIOP (mword_of_int 52 : mword 6, Regidx (mword_of_int 10), Regidx (mword_of_int 15), SLLI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_04f49223 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x04f49223 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 68 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 9), 2), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_07000613 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x07000613 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 112 : mword 12, zreg, Regidx (mword_of_int 12), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_07490663 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x07490663 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 108 : mword 13, Regidx (mword_of_int 20), Regidx (mword_of_int 18), BEQ), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_08054163 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x08054163 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 130 : mword 13, zreg, Regidx (mword_of_int 10), BLT), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0a87a703 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0a87a703 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 168 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), false, 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0f405a63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0f405a63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 244 : mword 13, Regidx (mword_of_int 20), zreg, BGE), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0ff00793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0ff00793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 255 : mword 12, zreg, Regidx (mword_of_int 15), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_142027f3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x142027f3 : mword 32) : M instruction) s
  = Some (CSRReg (mword_of_int 322 : mword 12, zreg, Regidx (mword_of_int 15), CSRRS), s).
Proof using . decode_bridge_ms_bv. Qed.

Lemma kd_14302673 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x14302673 : mword 32) : M instruction) s
  = Some (CSRReg (mword_of_int 323 : mword 12, zreg, Regidx (mword_of_int 12), CSRRS), s).
Proof using . decode_bridge_ms_bv. Qed.

Lemma kd_14d79073 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x14d79073 : mword 32) : M instruction) s
  = Some (CSRReg (mword_of_int 333 : mword 12, Regidx (mword_of_int 15), zreg, CSRRW), s).
Proof using . decode_bridge_ms_bv. Qed.

Lemma kd_15050913 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x15050913 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 336 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 18), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_15053503 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x15053503 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 336 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), false, 8), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_15898513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x15898513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 344 : mword 12, Regidx (mword_of_int 19), Regidx (mword_of_int 10), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_23352223 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x23352223 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 548 : mword 12, Regidx (mword_of_int 19), Regidx (mword_of_int 10), 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_30679073 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x30679073 : mword 32) : M instruction) s
  = Some (CSRReg (mword_of_int 774 : mword 12, Regidx (mword_of_int 15), zreg, CSRRW), s).
Proof using . decode_bridge_ms_bv. Qed.

Lemma kd_33f000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x33f000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2878 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_40f0053b s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x40f0053b : mword 32) : M instruction) s
  = Some (RTYPEW (Regidx (mword_of_int 15), zreg, Regidx (mword_of_int 10), SUBW), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_590a0a13 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x590a0a13 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1424 : mword 12, Regidx (mword_of_int 20), Regidx (mword_of_int 20), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_5da68693 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x5da68693 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1498 : mword 12, Regidx (mword_of_int 13), Regidx (mword_of_int 13), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_7a2000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x7a2000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 1954 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_87bfc0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x87bfc0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2082938 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_899fe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x899fe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2091160 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_8aa50513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x8aa50513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 2218 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_8e650513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x8e650513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 2278 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_96ffe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x96ffe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2091374 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_97dfe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x97dfe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2091388 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_9bcfe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x9bcfe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2089404 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_9d7ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x9d7ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095574 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_a10fe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa10fe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2089488 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_ad3ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xad3ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095826 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_b62ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xb62ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2093922 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_b81fc0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xb81fc0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2083712 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_b89ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xb89ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096008 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_bd0fb0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xbd0fb0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2077648 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_bdbfe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xbdbfe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2091994 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_c3250513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xc3250513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3122 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_c6c50513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xc6c50513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3180 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_cae48493 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xcae48493 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3246 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_caffe0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xcaffe0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2092206 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_cb9fd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xcb9fd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2088120 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_ccdff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xccdff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096332 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_d0648493 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xd0648493 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3334 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_e21ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xe21ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096672 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_e6843703 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xe6843703 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 3688 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 14), false, 8), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f0dfc0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf0dfc0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2084620 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f41ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf41ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096960 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f6040513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf6040513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3936 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 10), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f6841683 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf6841683 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 3944 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 13), false, 2), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f71fb0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf71fb0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2080624 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f8000713 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf8000713 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3968 : mword 12, zreg, Regidx (mword_of_int 14), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_fcf71fe3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfcf71fe3 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 8158 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BNE), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_fe843703 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfe843703 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 4072 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 14), false, 8), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_ff4df937 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xff4df937 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 1045727 : mword 20, Regidx (mword_of_int 18), LUI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_ff4fd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xff4fd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2086900 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_ffeff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xffeff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095102 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

