(* KernelDecode31.v -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for shard 31 of 32 of the kernel image's instruction words: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [kd_<word> / ke_<word>].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
From iris.program_logic Require Import lifting.
From iris.program_logic Require Import language.
Require Import Riscv.rv64d_types Riscv.rv64d.
Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.
Require Import RiscvLang RiscvExec RiscvFetchExec.
Require Import WpMmodeLeafBase.
Require Import WpDecodeBridge.
Require Import WpRvcBridge.
Require Import ExecCommon.
Local Open Scope Z_scope.
Import Defs.

Lemma kd_0712 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x0712 : mword 16)) s
  = Some (C_SLLI (mword_of_int 4, Regidx (mword_of_int 14)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_0791 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x0791 : mword 16)) s
  = Some (C_ADDI (mword_of_int 4, Regidx (mword_of_int 15)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_15fd s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x15fd : mword 16)) s
  = Some (C_ADDI (mword_of_int 63, Regidx (mword_of_int 11)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_2d05 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x2d05 : mword 16)) s
  = Some (C_ADDIW (mword_of_int 1, Regidx (mword_of_int 26)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_3a5d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x3a5d : mword 16)) s
  = Some (C_ADDIW (mword_of_int 55, Regidx (mword_of_int 20)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_459c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x459c : mword 16)) s
  = Some (C_LW (mword_of_int 2, Cregidx (mword_of_int 3), Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_459c s :
  exec (execute (C_LW (mword_of_int 2, Cregidx (mword_of_int 3), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 8 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 15), false, 4)), s).
Proof using . apply exec_execute_C_LW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_4701 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4701 : mword 16)) s
  = Some (C_LI (mword_of_int 0, Regidx (mword_of_int 14)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_4ff4 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x4ff4 : mword 16)) s
  = Some (C_LW (mword_of_int 23, Cregidx (mword_of_int 7), Cregidx (mword_of_int 5)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_4ff4 s :
  exec (execute (C_LW (mword_of_int 23, Cregidx (mword_of_int 7), Cregidx (mword_of_int 5)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 92 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 13), false, 4)), s).
Proof using . apply exec_execute_C_LW_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_60a2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x60a2 : mword 16)) s
  = Some (C_LDSP (mword_of_int 1, Regidx (mword_of_int 1)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_652c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x652c : mword 16)) s
  = Some (C_LD (mword_of_int 9, Cregidx (mword_of_int 2), Cregidx (mword_of_int 3)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_652c s :
  exec (execute (C_LD (mword_of_int 9, Cregidx (mword_of_int 2), Cregidx (mword_of_int 3)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 72 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 11), false, 8)), s).
Proof using . apply exec_execute_C_LD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_6798 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x6798 : mword 16)) s
  = Some (C_LD (mword_of_int 1, Cregidx (mword_of_int 7), Cregidx (mword_of_int 6)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_6798 s :
  exec (execute (C_LD (mword_of_int 1, Cregidx (mword_of_int 7), Cregidx (mword_of_int 6)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 8 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), false, 8)), s).
Proof using . apply exec_execute_C_LD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_68a8 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x68a8 : mword 16)) s
  = Some (C_LD (mword_of_int 10, Cregidx (mword_of_int 1), Cregidx (mword_of_int 2)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_68a8 s :
  exec (execute (C_LD (mword_of_int 10, Cregidx (mword_of_int 1), Cregidx (mword_of_int 2)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 80 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 10), false, 8)), s).
Proof using . apply exec_execute_C_LD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_69a2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x69a2 : mword 16)) s
  = Some (C_LDSP (mword_of_int 1, Regidx (mword_of_int 19)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_6ae2 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x6ae2 : mword 16)) s
  = Some (C_LDSP (mword_of_int 3, Regidx (mword_of_int 21)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_6cb8 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x6cb8 : mword 16)) s
  = Some (C_LD (mword_of_int 11, Cregidx (mword_of_int 1), Cregidx (mword_of_int 6)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_6cb8 s :
  exec (execute (C_LD (mword_of_int 11, Cregidx (mword_of_int 1), Cregidx (mword_of_int 6)))) s
  = Some (ExecuteAs (LOAD (mword_of_int 88 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 14), false, 8)), s).
Proof using . apply exec_execute_C_LD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_6d42 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x6d42 : mword 16)) s
  = Some (C_LDSP (mword_of_int 2, Regidx (mword_of_int 26)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_7402 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7402 : mword 16)) s
  = Some (C_LDSP (mword_of_int 4, Regidx (mword_of_int 8)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_790a s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x790a : mword 16)) s
  = Some (C_LDSP (mword_of_int 20, Regidx (mword_of_int 18)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_7c7d s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x7c7d : mword 16)) s
  = Some (C_LUI (mword_of_int 63, Regidx (mword_of_int 24)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_8636 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8636 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 12), Regidx (mword_of_int 13)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_8652 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8652 : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 12), Regidx (mword_of_int 20)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_87ce s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x87ce : mword 16)) s
  = Some (C_MV (Regidx (mword_of_int 15), Regidx (mword_of_int 19)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_8bbd s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x8bbd : mword 16)) s
  = Some (C_ANDI (mword_of_int 15, Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_8bbd s :
  exec (execute (C_ANDI (mword_of_int 15, Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (ITYPE (sign_extend' 12 (mword_of_int 15 : mword 6), creg2reg_idx (Cregidx (mword_of_int 7)), creg2reg_idx (Cregidx (mword_of_int 7)), ANDI)), s).
Proof using . apply exec_execute_C_ANDI_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_953e s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x953e : mword 16)) s
  = Some (C_ADD (Regidx (mword_of_int 10), Regidx (mword_of_int 15)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_96aa s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x96aa : mword 16)) s
  = Some (C_ADD (Regidx (mword_of_int 13), Regidx (mword_of_int 10)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_9a6e s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0x9a6e : mword 16)) s
  = Some (C_ADD (Regidx (mword_of_int 20), Regidx (mword_of_int 27)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_a031 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xa031 : mword 16)) s
  = Some (C_J (mword_of_int 6), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_a825 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xa825 : mword 16)) s
  = Some (C_J (mword_of_int 28), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_b7f1 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xb7f1 : mword 16)) s
  = Some (C_J (mword_of_int 2022), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_b7f5 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xb7f5 : mword 16)) s
  = Some (C_J (mword_of_int 2038), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_bfc5 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xbfc5 : mword 16)) s
  = Some (C_J (mword_of_int 2040), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_bff9 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xbff9 : mword 16)) s
  = Some (C_J (mword_of_int 2031), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_c3dd s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xc3dd : mword 16)) s
  = Some (C_BEQZ (mword_of_int 83, Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_c711 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xc711 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 6, Cregidx (mword_of_int 6)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_d375 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xd375 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 242, Cregidx (mword_of_int 6)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_d3b5 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xd3b5 : mword 16)) s
  = Some (C_BEQZ (mword_of_int 178, Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_dbdd s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xdbdd : mword 16)) s
  = Some (C_BEQZ (mword_of_int 219, Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_e99c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xe99c : mword 16)) s
  = Some (C_SD (mword_of_int 2, Cregidx (mword_of_int 3), Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_e99c s :
  exec (execute (C_SD (mword_of_int 2, Cregidx (mword_of_int 3), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (STORE (mword_of_int 16 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 11), 8)), s).
Proof using . apply exec_execute_C_SD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_f3da s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf3da : mword 16)) s
  = Some (C_SDSP (mword_of_int 60, Regidx (mword_of_int 22)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_f41c s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf41c : mword 16)) s
  = Some (C_SD (mword_of_int 5, Cregidx (mword_of_int 0), Cregidx (mword_of_int 7)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma ke_f41c s :
  exec (execute (C_SD (mword_of_int 5, Cregidx (mword_of_int 0), Cregidx (mword_of_int 7)))) s
  = Some (ExecuteAs (STORE (mword_of_int 40 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 8), 8)), s).
Proof using . apply exec_execute_C_SD_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.

Lemma kd_f526 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf526 : mword 16)) s
  = Some (C_SDSP (mword_of_int 21, Regidx (mword_of_int 9)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_f7d6 s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) ('b"1") = true ->
  exec (ext_decode_compressed (mword_of_int 0xf7d6 : mword 16)) s
  = Some (C_SDSP (mword_of_int 61, Regidx (mword_of_int 21)), s).
Proof using . intro H. rvc_oneshot s H. Qed.

Lemma kd_00010597 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00010597 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 16 : mword 20, Regidx (mword_of_int 11), AUIPC), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00023797 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00023797 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 35 : mword 20, Regidx (mword_of_int 15), AUIPC), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00052023 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00052023 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 0 : mword 12, zreg, Regidx (mword_of_int 10), 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00074503 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00074503 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 0 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 10), true, 1), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0017e793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0017e793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ORI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_009ba023 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x009ba023 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 0 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 23), 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00b67d63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00b67d63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 26 : mword 13, Regidx (mword_of_int 11), Regidx (mword_of_int 12), BGEU), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00d5179b s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00d5179b : mword 32) : M instruction) s
  = Some (SHIFTIWOP (mword_of_int 13 : mword 5, Regidx (mword_of_int 10), Regidx (mword_of_int 15), SLLIW), s).
Proof using . decode_bridge_ms_bv. Qed.

Lemma kd_00e687bb s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00e687bb : mword 32) : M instruction) s
  = Some (RTYPEW (Regidx (mword_of_int 14), Regidx (mword_of_int 13), Regidx (mword_of_int 15), ADDW), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00e78c23 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00e78c23 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 24 : mword 12, Regidx (mword_of_int 14), Regidx (mword_of_int 15), 1), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_00f701a3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x00f701a3 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 3 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 14), 1), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_01f6579b s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x01f6579b : mword 32) : M instruction) s
  = Some (SHIFTIWOP (mword_of_int 31 : mword 5, Regidx (mword_of_int 12), Regidx (mword_of_int 15), SRLIW), s).
Proof using . decode_bridge_ms_bv. Qed.

Lemma kd_02492503 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02492503 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 36 : mword 12, Regidx (mword_of_int 18), Regidx (mword_of_int 10), false, 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_02d76b63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02d76b63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 54 : mword 13, Regidx (mword_of_int 13), Regidx (mword_of_int 14), BLTU), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_02f76663 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x02f76663 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 44 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BLTU), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_032585b3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x032585b3 : mword 32) : M instruction) s
  = Some (MUL (Regidx (mword_of_int 18), Regidx (mword_of_int 11), Regidx (mword_of_int 11), mulop_mul), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0369ff63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0369ff63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 62 : mword 13, Regidx (mword_of_int 22), Regidx (mword_of_int 19), BGEU), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_06850513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x06850513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 104 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_06f70663 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x06f70663 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 108 : mword 13, Regidx (mword_of_int 15), Regidx (mword_of_int 14), BEQ), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0a054b63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0a054b63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 182 : mword 13, zreg, Regidx (mword_of_int 10), BLT), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0c0027b7 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0c0027b7 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 49154 : mword 20, Regidx (mword_of_int 15), LUI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0cd7ea63 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0cd7ea63 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 212 : mword 13, Regidx (mword_of_int 13), Regidx (mword_of_int 15), BLTU), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_0e078263 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x0e078263 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 228 : mword 13, zreg, Regidx (mword_of_int 15), BEQ), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_10001637 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x10001637 : mword 32) : M instruction) s
  = Some (UTYPE (mword_of_int 65537 : mword 20, Regidx (mword_of_int 12), LUI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_16450513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x16450513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 356 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_1dd000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x1dd000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2524 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_1ff7f793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x1ff7f793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 511 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ANDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_20052e23 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x20052e23 : mword 32) : M instruction) s
  = Some (STORE (mword_of_int 540 : mword 12, zreg, Regidx (mword_of_int 10), 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_23450513 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x23450513 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 564 : mword 12, Regidx (mword_of_int 10), Regidx (mword_of_int 10), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_2de000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x2de000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 734 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_34813103 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x34813103 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 840 : mword 12, Regidx (mword_of_int 2), Regidx (mword_of_int 2), false, 8), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_40e90933 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x40e90933 : mword 32) : M instruction) s
  = Some (RTYPE (Regidx (mword_of_int 14), Regidx (mword_of_int 18), Regidx (mword_of_int 18), SUB), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_413010ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x413010ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 7186 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_413484b3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x413484b3 : mword 32) : M instruction) s
  = Some (RTYPE (Regidx (mword_of_int 19), Regidx (mword_of_int 9), Regidx (mword_of_int 9), SUB), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_465000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x465000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 3172 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_51f000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x51f000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 3358 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_5f5000ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x5f5000ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 3572 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_66c010ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x66c010ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 5740 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_78858593 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x78858593 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 1928 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_907ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0x907ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095366 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_a4e4b483 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa4e4b483 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 2638 : mword 12, Regidx (mword_of_int 9), Regidx (mword_of_int 9), false, 8), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_a54fd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa54fd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2085460 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_a8dfd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa8dfd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2087564 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_a8efd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa8efd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2085518 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_a8fff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xa8fff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095758 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_b64fd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xb64fd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2085732 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_b82ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xb82ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2093954 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_c60fc0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xc60fc0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2081888 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_cc87a783 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xcc87a783 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 3272 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), false, 4), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_d17ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xd17ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096406 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_d5c58593 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xd5c58593 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3420 : mword 12, Regidx (mword_of_int 11), Regidx (mword_of_int 11), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_d63ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xd63ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096482 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_dbdff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xdbdff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096572 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_df043583 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xdf043583 : mword 32) : M instruction) s
  = Some (LOAD (mword_of_int 3568 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 11), false, 8), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_df6a8a93 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xdf6a8a93 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3574 : mword 12, Regidx (mword_of_int 21), Regidx (mword_of_int 21), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_ea9ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xea9ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096808 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f1840613 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf1840613 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3864 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 12), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f4878793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf4878793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3912 : mword 12, Regidx (mword_of_int 15), Regidx (mword_of_int 15), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f51ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf51ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2096976 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f71ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf71ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2097008 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f85ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf85ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2097028 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f9460793 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf9460793 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3988 : mword 12, Regidx (mword_of_int 12), Regidx (mword_of_int 15), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_f9f40c13 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xf9f40c13 : mword 32) : M instruction) s
  = Some (ITYPE (mword_of_int 3999 : mword 12, Regidx (mword_of_int 8), Regidx (mword_of_int 24), ADDI), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_fadfd0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfadfd0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2088876 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_fb0ff0ef s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfb0ff0ef : mword 32) : M instruction) s
  = Some (JAL (mword_of_int 2095024 : mword 21, Regidx (mword_of_int 1)), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_fc0b1de3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfc0b1de3 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 8154 : mword 13, zreg, Regidx (mword_of_int 22), BNE), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_fd351ee3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfd351ee3 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 8156 : mword 13, Regidx (mword_of_int 19), Regidx (mword_of_int 10), BNE), s).
Proof using . decode_bridge_ms. Qed.

Lemma kd_fee79ae3 s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->
  exec (ext_decode (mword_of_int 0xfee79ae3 : mword 32) : M instruction) s
  = Some (BTYPE (mword_of_int 8180 : mword 13, Regidx (mword_of_int 14), Regidx (mword_of_int 15), BNE), s).
Proof using . decode_bridge_ms. Qed.

