(* ====================================================================== *)
(* ResvAxioms.v -- THE LR/SC RESERVATION PLATFORM HOOKS, AT THE *TERM*      *)
(* LEVEL.  NO LONGER AXIOMS: SINCE THE `coq:`-BINDING CHANGE THESE ARE      *)
(* THEOREMS, PROVED BY [reflexivity].                                       *)
(*                                                                          *)
(* WHAT CHANGED, AND WHY THE FILE KEPT ITS NAME.  [load_reservation] and    *)
(* [cancel_reservation] used to be declared by the generated model as opaque*)
(* *Axioms* (they sat at rv64d.v:21793,21802 before this change), because   *)
(* sail's Rocq backend emits one for every `val` with no Sail body and no   *)
(* `coq:` extern binding.  The pinned sail-riscv fork now gives them that   *)
(* binding, so sail emits nothing and [model-xv6iris/xv6iris_extras.v]      *)
(* supplies the bodies -- both [returnm tt], which is EXACT and not a       *)
(* simplification, since the LR/SC reservation set is platform state outside*)
(* [regstate] / [mstate] and so the hooks move nothing this development can *)
(* observe.  The two statements below are therefore unchanged in FORM and   *)
(* unchanged in NAME -- every consumer still writes [rewrite                *)
(* load_reservation_term] -- but they are now [Lemma]s rather than [Axiom]s,*)
(* and they left the [Print Assumptions] baseline in `SystemAssumptions.v`  *)
(* when they did.  THE FILE IS KEPT (rather than deleted and its two names  *)
(* inlined at the use sites) precisely so that this history, and the        *)
(* reasoning below about WHY the statement is at the term level, stays      *)
(* attached to them.                                                        *)
(*                                                                          *)
(* WHY THE STATEMENT MUST BE AT THE TERM LEVEL, AND NOT AT [exec].          *)
(* The obvious (and, until this file, the actual) shape was a claim about   *)
(* the *interpreter's answer*:                                              *)
(*                                                                          *)
(*   exec (load_reservation a w) s = Some (tt, s).                          *)
(*                                                                          *)
(* That is enough while a hart steps a WHOLE CYCLE at a time -- the only    *)
(* thing anyone asks of the hook is what [exec] returns for it.  It is NOT  *)
(* enough under per-node stepping (design/main-cycle-port.md): the language *)
(* steps one monad NODE at a time and [RiscvLang.mnode_step] matches on the *)
(* monad's CONSTRUCTORS, so an application of an opaque constant has no arm *)
(* at all and the configuration is IRREDUCIBLE.  Adequacy is [NotStuck] and *)
(* arbitrary user code may execute [lr]/[sc], so an exec-level fact would   *)
(* leave a genuine SAFETY HOLE -- not an inconvenience -- in the user tier. *)
(* A fact about the TERM tells every consumer (the machine, [exec], the     *)
(* footprint walkers [goodb]/[goodmb]/[hfrun]/[hmrun]) the same thing at    *)
(* once: the hook IS [returnm tt], which every one of them can step.  That  *)
(* argument is why the realisation in [xv6iris_extras.v] is [returnm tt]    *)
(* and not, say, some other unit-valued term.                               *)
(*                                                                          *)
(* THE exec-LEVEL COROLLARIES still live in                                 *)
(* [UserMemAccess.exec_load_reservation] / [_cancel_reservation], each one  *)
(* line from the lemma here, so no consumer's proof moved across the        *)
(* change.                                                                  *)
(*                                                                          *)
(* WHAT IS *NOT* PROVED HERE.  Nothing about the reservation's CONTENT:     *)
(* [match_reservation] and [valid_reservation] are [bool]-valued and are    *)
(* destructed both ways wherever an SC or a wake-up decision reads them.    *)
(* Sail declares them `pure`, so within one Rocq evaluation each is a FIXED *)
(* function and the model cannot express a reservation set that changes;    *)
(* [xv6iris_extras.v] realises them over the two [Parameter]s               *)
(* [resv_matches] / [resv_is_valid], which are now the ONLY assumed content *)
(* of the reservation story and the only two reservation entries left in    *)
(* the audit.  Only the two [M unit]-valued hooks, whose whole observable   *)
(* effect on the modelled architectural state (sregs / mem / mdev) is nil,  *)
(* are pinned here.                                                         *)
(*                                                                          *)
(* THE OTHER OPAQUE [M]-VALUED HOOKS are [plat_term_read] (HTIF input) and  *)
(* [get_16_random_bits] (the Zkr seed CSR, illegal at U).  Neither is       *)
(* realised here, and for the same reason: each one's result is CONSUMED, so*)
(* any realisation would fabricate data, and a hart that reaches one should *)
(* get stuck loudly rather than proceed quietly.  They differ only in WHERE *)
(* the assumption sits -- [plat_term_read] is declared in the fork's        *)
(* riscv_extras.v (it has a `coq:` binding, so sail emits nothing for it),  *)
(* while [get_16_random_bits] has no binding and is still generated into    *)
(* rv64d.v.  ([plat_term_write] is the exception and IS realised in         *)
(* xv6iris_extras.v, since the byte it writes leaves the modelled state     *)
(* untouched.)                                                              *)
(*                                                                          *)
(* This file requires nothing but the generated model and the realisations, *)
(* so it can sit below the language file and be shared by the boot cone and *)
(* the U-mode tier.  IMPORT ORDER TRAP (as in ArchReset.v): [SailStdpp.Base]*)
(* re-exports Prompt_monad's [read_reg]/[write_reg], so [Import Defs] must  *)
(* come LAST.                                                               *)
(* ====================================================================== *)
From Stdlib Require Import ZArith.
Require Import SailStdpp.Base.
Require Import Riscv.rv64d_types Riscv.xv6iris_extras Riscv.rv64d.
Import Defs.

Lemma load_reservation_term :
  forall (a : mword (if 64 =? 32 then 34 else 64)) (n : Z),
    load_reservation a n = Defs.returnm tt.
Proof. reflexivity. Qed.

Lemma cancel_reservation_term :
  forall (u : unit), cancel_reservation u = Defs.returnm tt.
Proof. reflexivity. Qed.
