(* ====================================================================== *)
(* SystemAssumptions.v -- THE ASSUMPTION AUDIT of the system theorem.      *)
(*                                                                        *)
(* [Print Assumptions] on [SystemAdequacy.xv6_fs_adequacy_xv6Σ]: the one   *)
(* check that sees through every functor and every seal, and so the only   *)
(* thing that can tell you what the system theorem actually rests on.      *)
(*                                                                        *)
(* THE TARGET IS THE THEOREM WITH NOTHING LEFT AS A PREMISE.  It used to   *)
(* be [xv6_power_adequacy_xv6Σ], which is the same theorem with the image  *)
(* hypothesis [Himg] still open -- a smaller print, but an audit of a      *)
(* conditional statement.  [xv6_fs_adequacy_xv6Σ] discharges every image   *)
(* hypothesis at the 2,048,000 bytes mkfs actually wrote, so its axiom     *)
(* list is the whole story and there is nothing behind it.                 *)
(*                                                                        *)
(* EXPECT EXACTLY THIRTEEN, and the split matters:                        *)
(*                                                                        *)
(*   1  [functional_extensionality_dep]                                    *)
(*   2  [xv6iris_extras.resv_matches] / [_is_valid] -- the LR/SC           *)
(*      reservation predicates, this project's own [Parameter]s            *)
(*  10  Rocq's [PrimString]/[PrimInt63] primitives                         *)
(*      ([PrimString.string]/[.get]/[.cat], [PrimInt63.int]/[.eqb]/[.sub]/ *)
(*      [.lsl]/[.lsr]/[.land]/[.lor])                                      *)
(*                                                                        *)
(* THE TEN ARE STRUCTURAL, NOT A REGRESSION.  Any constant naming the      *)
(* literal image drags them in -- the same set appears on [ElfKernel.v],   *)
(* [ElfUser.v] and [FsImgCheck.v] -- because [FsImgDisk.fsimg_dk] is a     *)
(* [PrimString]-backed constant.  They are listed by name above and in     *)
(* durable-notes' "adequacy-print baseline" precisely so a reader can tell *)
(* them from something new.                                               *)
(*                                                                        *)
(* ANYTHING ELSE IS A REGRESSION -- including a [Link*] entry, since the   *)
(* deliberately-unproven kernel functions are all discharged in the        *)
(* theorem's cone as of 2026-08-22 (xv6-bump-playbook.md §7.2).            *)
(*                                                                        *)
(* IT USED TO BE EIGHT AT THE IMAGE-FREE TARGET.  Five of those were       *)
(* Sail-generated axioms nobody in this tree declared: sail's Rocq backend *)
(* emits an [Axiom] for every `val` with no body and no `coq:` extern      *)
(* binding, and [load_reservation], [cancel_reservation],                  *)
(* [match_reservation], [valid_reservation] and [plat_term_write] all      *)
(* qualified.  The pinned sail-riscv fork now binds them and               *)
(* [model-xv6iris/xv6iris_extras.v] realises them, which retired three of  *)
(* the five outright (their effect on the modelled state is nil) and       *)
(* re-expressed the other two as this project's own [Parameter]s -- so     *)
(* what is left assumed about the reservation is exactly its CONTENT,      *)
(* under names that a reader of the audit can look up.  The two            *)
(* [ResvAxioms] term-level entries became [reflexivity] lemmas in the same *)
(* change.                                                                 *)
(*                                                                        *)
(* WHY IT IS A FILE OF ITS OWN, AND ONE [iris/_CoqProject] DOES NOT LIST.  *)
(* The command walks every opaque proof term in the transitive cone,       *)
(* re-cooking each one out of its section and re-substituting it through   *)
(* its functor as it goes; measured at ~379 s, on the strictly serial      *)
(* build tail, and it would be paid by every developer on every build.  So *)
(* the audit is compiled by `make audit` instead, and by CI after the      *)
(* build -- concurrently with [EchoAssumptions.v], the application         *)
(* theorem's audit, whose cone this one does not contain (the two outputs  *)
(* land in the run's step summary).  The commented row                     *)
(* in [iris/_CoqProject] is what tells the coverage checker this file is   *)
(* out of the coq_makefile build on purpose rather than by accident.       *)
(* claude-notes/optimization.md has the measurements.                      *)
(*                                                                        *)
(* KEEP IT TO ONE [Print Assumptions].  Consecutive calls share NOTHING -- *)
(* measured back to back in one process, 94.5 s then 100.6 s -- so a       *)
(* second audit here does not ride along on the first, it doubles the      *)
(* bill.                                                                   *)
(*                                                                        *)
(* THE OTHER HALF OF THE TRUSTED BASE -- what a reader must READ for the   *)
(* statement to MEAN what they think -- is not here and is not an axiom    *)
(* question.  See tools/tcb/ and claude-notes/design/adequacy.md.          *)
(* ====================================================================== *)
Require Import SystemAdequacy.

Print Assumptions xv6_fs_adequacy_xv6Σ.
