(* ====================================================================== *)
(* TreeAssumptions.v -- THE ASSUMPTION AUDIT of the TREE APPLICATION's     *)
(* era-0 obligation.                                                      *)
(*                                                                        *)
(* [Print Assumptions] on [UTreeAdequacy.tree_adequacy_treeΣ] (lane TL-5;  *)
(* it was [TreeImg.tree_Happ_init] while [Hinit_boot] was open, and the    *)
(* retarget is the only change this file needed):                          *)
(* [App.xv6_app_adequacy] at [AppTree.app_tree], CLOSED -- the functor     *)
(* list a concrete [treeAppΣ], the disk the literal image mkfs wrote, and  *)
(* every obligation of the record discharged, era 0's claim               *)
(* ([TreeImg.tree_Happ_init]) and the first process's exec bundle          *)
(* ([UTreeAdequacy.tree_Hinit_boot]) included.                             *)
(*                                                                        *)
(* WHAT THE STATEMENT SAYS, AND WHAT THE CONE CHECKS.  The statement is    *)
(* reducibility (the application's [app_phi] is [True] -- [UTreeAdequacy]'s *)
(* header says why no stronger PURE conclusion exists while the taint is   *)
(* a resource no trace event witnesses).  What the CONE checks is the      *)
(* application: [AppTree.tree_pred] -- the live namespace is a rooted tree *)
(* partitioned among its owners, or the taint records an unpaid mover --   *)
(* pays every obligation of the whole-system theorem at the real image.    *)
(* The era's first process is not verified against the claim and the claim *)
(* records that at boot (design/user-tree.md section 8.4's arm); a         *)
(* verified <init> is section 9.2's worklist and would move the mint,      *)
(* not the target of this audit.                                          *)
(*                                                                        *)
(* WHY IT IS A THIRD AUDIT FILE, beside [SystemAssumptions.v] and          *)
(* [EchoAssumptions.v]: for [EchoAssumptions.v]'s own reason.  Neither     *)
(* cone contains this one -- the system theorem walks no application tier  *)
(* at all, and the echo theorem walks [AppEcho]/[EchoOut]/[USh*] and       *)
(* never [AppTree]/[TreeView]/[TreeMove]/[TreeImg].  A grep for [Axiom]    *)
(* and [Admitted] cannot see a sealed [Spec*] module [Parameter]; this is  *)
(* the check that does.                                                   *)
(*                                                                        *)
(* WHY IT IS OUT OF [iris/_CoqProject], same as its two siblings:          *)
(* [Print Assumptions] re-cooks every opaque proof term in the transitive  *)
(* cone, and paying that on every developer's every build is not worth it. *)
(* Compiled by `make audit-tree` / `make audit-tree-only` instead.         *)
(*                                                                        *)
(* KEEP IT TO ONE [Print Assumptions]: consecutive calls share nothing, so *)
(* a second command here would double the bill rather than ride along.     *)
(*                                                                        *)
(* THE OTHER HALF OF THE TRUSTED BASE -- what a reader must READ for the   *)
(* statement to MEAN what they think -- is not an axiom question.  For     *)
(* this theorem it is above all [TreeView.aview_tree_wf] /                 *)
(* [TreeView.aview_rooted] and [AppTree.tree_pred]: the claim IS the       *)
(* specification.  See tools/tcb/ and claude-notes/design/user-tree.md.    *)
(* ====================================================================== *)
Require Import UTreeAdequacy.

Print Assumptions tree_adequacy_treeΣ.
