#!/usr/bin/env python3
"""gen_code.py -- GENERATE the iris/ instruction-decode layer from the image.

Emits, from kernel-rocq/{KernelSyms,KernelInstrs}.v alone:

  iris/KernelDecode.v   one decode fact per DISTINCT instruction word the
                        covered functions contain, keyed by the word:
                          kd_<hex>   exec (ext_decode[_compressed] w) = Some (ast, s)
                          ke_<hex>   the leaf-form expansion, for the compressed
                                     load/store/ANDI/OR forms whose WP leaf
                                     takes the resolved shape
  iris/Code<F>.v        per covered function, one
                          kernel_text -* instr <sym + off> <rvc> <ast>
                        fact per instruction, named <prefix><off>.

Nothing here parses an existing proof: the AST comes from tools/riscv_ast.py
(a decoder), the addresses from KernelSyms, the bytes from KernelInstrs, and
the file/prefix layout from the manifest below.  Re-running after an xv6
update rewrites the whole layer.

The single KernelDecode.v is a known serialization point -- every Code<F>.v
depends on it, so nothing compiles until it finishes.  Measured per-lemma
cost on this tree: a compressed decode is ~37 ms (rvc_oneshot), a BASE decode
~293 ms (decode_bridge_ms), so the base facts dominate.  Sharding it is
planned; the shard key should be the word, so a Code file's dependencies stay
computable without parsing.
"""

import argparse
import gen_consts
import hashlib
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import riscv_ast as R

# Compressed ops whose exec bridge is a per-word `_leaf` application rather
# than a single generic lemma.
LEAF_OPS = {'C_LW', 'C_LD', 'C_SW', 'C_SD', 'C_ANDI', 'C_OR'}

# Words whose decode fact is HAND-WRITTEN and stays that way, because its
# hypotheses are not the generic (MISA_C, cfg_ok) pair.  The generator emits
# the instr fact against the existing lemma instead of a kd_<word>.
#   acquire's [amoswap.w.aq a5,a5,(s1)] -- guarded by priv_mSU + Misa_A.
OVERRIDES = {
    (0x0cf4a7af, 32): ('amoswap_acq_ast', 'amodec', 'Require Import WpAmo.'),
}

HEADER = """(* %(file)s -- AUTO-GENERATED by tools/gen_code.py.  DO NOT EDIT BY HAND.

   The instruction-DECODE layer for %(what)s: for every instruction, a
   [kernel_text -* instr pc <is_rvc> <AST>] fact named [%(names)s].
   Addresses are symbol-relative, so a relayout moves them for free; the
   encoding words and their decoded immediates come from the tracked dump,
   which is why this file is generated rather than maintained.

   Regenerate with:  make gen-code                                        *)
%(imports)s
Local Open Scope Z_scope.
Import Defs.
"""

# ---------------------------------------------------------------------------
# Imports.
#
# A generated file's imports are DERIVED from what that file actually says --
# never one fixed header every file gets.  The two kinds of file here use
# disjoint vocabularies (a decode shard states `exec (ext_decode w) s = ...`, a
# Code file states `kernel_text -* instr ...`), and the decode shards a Code
# file reaches are the ones holding ITS words, so a fixed header is unused
# imports by construction.
#
# Keeping this exact is what keeps the nightly dead-import sweep
# (.github/workflows/dead-imports.yml) off these files: it deletes
# provably-unused imports and pushes the result, and it has no exclusion for
# generated files -- an exclusion would hide drift here rather than fix it.  A
# sweep commit touching a generated file is a bug report about the table below.
#
# Every entry below is NEEDED by the same test that sweep applies: delete it,
# recompile the file, watch it fail.  Modules that survive that test, and so
# are deliberately absent: Stdlib.ZArith (Z_scope arrives with SailStdpp),
# stdpp.bitvector.definitions, iris.proofmode.proofmode, the four
# SailStdpp.ConcurrencyInterface* modules, Riscv.riscv_extras, KernelRvcDecode,
# and, in a shard, the two `From Kernel Require`s -- a shard names no symbol and
# no byte.

# What both kinds need.  `lifting` looks gratuitous in a shard, which states no
# WP at all, but removing it breaks the build in both kinds -- it is reached
# for an instance, not a name.
COMMON_IMPORTS = [
    'From iris.program_logic Require Import lifting.',
    'From iris.program_logic Require Import language.',
    'Require Import Riscv.rv64d_types Riscv.rv64d.',
    'Require Import SailStdpp.Base SailStdpp.TypeCasts SailStdpp.Values SailStdpp.MachineWord.',
]

# A Code file's own vocabulary: `instr` (InstrBytes), `kernel_text` / `mk_rvc`
# / `mk_base` (KernelText), the `exec_execute_<op>` bridges (WpMmodeLeafBase),
# and the symbol addresses (KernelSyms; KernelInstrs comes with the bytes
# KernelText's `kernel_text` is stated over).
CODE_IMPORTS = [
    'Require Import RiscvLang RiscvPtsto.',
    'Require Import InstrBytes.',
    'Require Import KernelText.',
    'Require Import WpMmodeLeafBase.',
    'From Kernel Require KernelInstrs.',
    'From Kernel Require KernelSyms.',
]

# A decode shard's: `exec` / `ext_decode` (RiscvExec, RiscvFetchExec) and the
# `cfg_ok` / MISA_C side of the base hypotheses (WpMmodeLeafBase).  The two
# proof tactics are conditional -- see NAME_IMPORTS.
SHARD_IMPORTS = [
    'Require Import RiscvLang RiscvExec RiscvFetchExec.',
    'Require Import WpMmodeLeafBase.',
]

# Imports a file needs only when the text it emits mentions the name -- checked
# against the emitted body rather than predicted, so an emission change cannot
# leave the header behind.  `decode_bridge_ms` also matches `decode_bridge_ms_bv`
# and `mulop_mul` reaches ExecCommon, which is why a MUL is the only instruction
# whose Code file needs it.
NAME_IMPORTS = [
    ('decode_bridge_ms', 'Require Import WpDecodeBridge.'),
    ('rvc_oneshot', 'Require Import WpRvcBridge.'),
    ('mulop_mul', 'Require Import ExecCommon.'),
    ('exec_execute_C_SUBW', 'Require Import UserExecFacts.'),
]


def write_if_changed(path, text):
    """Write only when the content actually moved.

    An unconditional rewrite stamps a new mtime on every generated file, so a
    `make check-decode` run after a green build forces a from-scratch
    recompile of the whole decode layer's cone -- which is what made the
    check something you had to remember to run BEFORE the build.  Output is
    deterministic, so "unchanged" is exactly "nothing to rebuild"."""
    try:
        if open(path).read() == text:
            return False
    except OSError:
        pass
    open(path, 'w').write(text)
    return True


def header(path, what, names, imports, body):
    """Render the file header, keeping only the imports [body] justifies."""
    imports = list(imports)
    for name, line in NAME_IMPORTS:
        if name in body and line not in imports:
            imports.append(line)
    return HEADER % dict(file=os.path.basename(path), what=what, names=names,
                         imports='\n'.join(COMMON_IMPORTS + imports))


def load_syms(path):
    d = {}
    for line in open(path):
        m = re.match(r'Definition (\w+) : Z := (0x[0-9a-fA-F]+)%Z\.', line)
        if m:
            d[m.group(1)] = int(m.group(2), 16)
    return d


def load_bytes(path):
    d = {}
    pat = re.compile(r'\(\((0x[0-9a-fA-F]+)\)%Z, Z_to_bv 8 \((0x[0-9a-fA-F]+)\)%Z\)')
    for line in open(path):
        m = pat.search(line)
        if m:
            d[int(m.group(1), 16)] = int(m.group(2), 16)
    return d


def word_at(by, a, n):
    v = 0
    for i in range(n):
        b = by.get(a + i)
        if b is None:
            return None
        v |= b << (8 * i)
    return v


# Alignment padding gcc leaves between functions.  A symbol's range runs to
# the NEXT symbol, so it can include these; no proof ever steps them, and
# emitting facts for them would need an exec lemma for C_NOP that does not
# (and need not) exist.
PADDING = {0x0000, 0x0001}


def instructions(by, lo, hi):
    """Walk [lo,hi) yielding (addr, word, width), stopping at the padding.

    A symbol's range runs to the NEXT symbol, so it includes the alignment
    bytes gas leaves after the real code -- and those decode as plausible
    instructions, so a naive walk invents them.  kernelvec ends with `sret` at
    +0x4c; +0x50 onward is padding that decoded as c.nop and three more
    "instructions" before the next symbol.

    Padding always FOLLOWS the code, so truncate at the first padding word
    rather than only trimming the tail: a lone c.nop does not end a run of it.
    (C_NOP could not be emitted anyway -- the model's execute_C_NOP returns
    RETIRE_SUCCESS directly, not an ExecuteAs, so mk_rvc cannot state it.)"""
    out = []
    for rec in _walk(by, lo, hi):
        if rec[2] == 16 and rec[1] in PADDING:
            break
        out.append(rec)
    return out


def _walk(by, lo, hi):
    a = lo
    while a < hi:
        h = word_at(by, a, 2)
        if h is None:
            return
        if (h & 3) == 3:
            w = word_at(by, a, 4)
            if w is None:
                return
            yield a, w, 32
            a += 4
        else:
            yield a, h, 16
            a += 2


def decode(w, width):
    if (w, width) in OVERRIDES:
        ast, dec, _ = OVERRIDES[(w, width)]
        return (ast, None, None)
    if width == 32:
        ast = R.decode_base(w)
        return None if ast is None else (ast, None, None)
    r = R.decode_compressed(w)
    return None if r is None else (r[0], r[1], r[2])


# Sized to the CI runner's core count, not to the lemma count: the shards have
# no dependency on each other, so they are the build's widest parallel step and
# a core past SHARDS has nothing from this layer to do.  There is a floor to
# what splitting further buys, though -- every shard pays the same fixed cost
# to load the Sail model before it proves anything, and that cost is per FILE.
SHARDS = 32


def shard_of(word):
    """Which KernelDecode<NN>.v a word's lemmas live in.

    Keyed on the WORD, not on position: adding or removing an instruction then
    lands in ONE shard and leaves the others byte-identical, so an incremental
    rebuild after a re-dump recompiles a fraction rather than the lot.  A
    positional split (round-robin over a sorted list) would rewrite every shard
    on any change.  Changing SHARDS re-keys every word, so it rewrites the
    whole layer -- shards and the Code files naming them alike.

    It has to be a MIXING hash, not `word % SHARDS`: a RISC-V base opcode
    almost always ends in 0b0011 (0x13, 0x23, 0x03, 0x63, 0x33, 0x73), so the
    low bits put 836 of 1383 base lemmas -- the expensive kind -- in one
    bucket and left others empty."""
    h = hashlib.blake2b(b'%d' % word, digest_size=4).digest()
    return int.from_bytes(h, 'big') % SHARDS


def _decode_lemmas(w, width, exp, cast, op, L):
    if width == 16:
        L.append('Lemma kd_%04x s : eq_vec (_get_Misa_C (register_lookup misa s.(sregs))) (\'b"1") = true ->' % w)
        L.append('  exec (ext_decode_compressed (mword_of_int 0x%04x : mword 16)) s' % w)
        L.append('  = Some (%s, s).' % cast)
        L.append('Proof using . intro H. rvc_oneshot s H. Qed.')
        if op in LEAF_OPS:
            L.append('')
            L.append('Lemma ke_%04x s :' % w)
            L.append('  exec (execute (%s)) s' % cast)
            L.append('  = Some (ExecuteAs (%s), s).' % exp)
            L.append('Proof using . apply exec_execute_%s_leaf; first [ apply bv_eq; vm_compute; reflexivity | vm_compute; reflexivity ]. Qed.' % op)
    else:
        L.append('Lemma kd_%08x s : register_lookup misa (sregs s) = MISA_C -> cfg_ok s ->' % w)
        L.append('  exec (ext_decode (mword_of_int 0x%08x : mword 32) : M instruction) s' % w)
        L.append('  = Some (%s, s).' % exp)
        # FENCE/FENCE.I pred-succ nibbles and a CSR number arrive as SLICES of
        # the word while the AST states them as [mword_of_int n]; only bv_eq
        # closes that pair, so those words need the _bv bridge.
        bridge = ('decode_bridge_ms_bv'
                  if exp.startswith(('FENCE (', 'FENCEI (', 'CSRReg (', 'CSRImm (', 'SHIFTIWOP ('))
                  else 'decode_bridge_ms')
        L.append('Proof using . %s. Qed.' % bridge)
    L.append('')


def emit_decode_file(words, iris):
    """One decode fact per distinct word, split across SHARDS files.

    A single file was 116 s and 1.7 GB, and EVERY Code<F>.v depends on it, so
    it sat squarely on the build's critical path.  The shards compile in
    parallel; a generated Code file imports the shards holding its own words
    (see code_imports), and KernelDecode.v is a facade that Require Exports all
    of them, for the hand-written files that just want the lot."""
    buckets = {i: [] for i in range(SHARDS)}
    for (w, width) in sorted(words):
        if (w, width) in OVERRIDES:
            continue
        exp, cast, op = words[(w, width)]
        _decode_lemmas(w, width, exp, cast, op, buckets[shard_of(w)])

    for i, L in sorted(buckets.items()):
        path = os.path.join(iris, 'KernelDecode%02d.v' % i)
        body = '\n'.join(L)
        head = header(
            path,
            'shard %d of %d of the kernel image\'s instruction words' % (i, SHARDS),
            'kd_<word> / ke_<word>', SHARD_IMPORTS, body)
        write_if_changed(path, head + '\n' + body + '\n')

    facade = ['(* KernelDecode.v -- AUTO-GENERATED by tools/gen_code.py.',
              '',
              '   A facade over the %d shards.  The decode facts are split so they' % SHARDS,
              '   compile in parallel -- one file was 116 s on the critical path that',
              '   every Code<F>.v waits behind -- and a word is assigned by its own',
              '   value, so a re-dump rewrites only the shards it actually touches.',
              '',
              '   The generated Code<F>.v files name the shards they use directly;',
              '   this is for hand-written consumers, which see all of them.       *)']
    facade += ['Require Export KernelDecode%02d.' % i for i in range(SHARDS)]
    write_if_changed(os.path.join(iris, 'KernelDecode.v'), '\n'.join(facade) + '\n')
    n16 = sum(1 for k in words if k[1] == 16)
    return n16, len(words) - n16


def code_imports(fams, by):
    """The decode facts THIS Code file reaches, plus any override's home.

    Not the `KernelDecode` facade: a Code file uses the shards holding its own
    words and nothing the other ones forward, so the facade is fifteen-odd
    imports contributing no name.  Naming the shards directly is also what lets
    a re-dump that lands in one shard leave the rest of the tree's dependencies
    untouched -- the point of keying the shards by word in the first place."""
    shards, over = set(), []
    for _, _, lo, hi, _ in fams:
        for _, w, wd in instructions(by, lo, hi):
            if (w, wd) in OVERRIDES:
                req = OVERRIDES[(w, wd)][2]
                if req not in over:
                    over.append(req)
            else:
                shards.add(shard_of(w))
    return (CODE_IMPORTS
            + ['Require Import KernelDecode%02d.' % i for i in sorted(shards)]
            + over)


def emit_code_file(path, fams, syms, by, decoded):
    """fams: [(symbol, prefix, lo, hi)] sharing one Code file."""
    what = ' / '.join(f for f, _, _, _, _ in fams)
    pres = ' / '.join('%s<off>' % p for _, p, _, _, _ in fams)
    L = []
    L.append('Section %s.' % os.path.basename(path)[:-2])
    L.append('  Context `{!riscvGS Σ}.')
    L.append('  Context `{GEN : GenId} `{CID : CpuId}.')
    L.append('')
    n = 0
    for sym, pre, lo, hi, wid in fams:
        L.append('  (* ---- %s @ KernelSyms.%s, %d bytes ---- *)' % (sym, sym, hi - lo))
        L.append('')
        for a, w, width in instructions(by, lo, hi):
            off = a - lo
            exp, cast, op = decoded[(w, width)]
            rvc = 'true' if width == 16 else 'false'
            pc = 'KernelSyms.%s' % sym if off == 0 else '(KernelSyms.%s + 0x%x)' % (sym, off)
            bare = (w, width) in OVERRIDES
            astt = exp if bare else '(%s)' % exp
            L.append('  Lemma %s%0*x : kernel_text -∗ instr (mword_of_int %s : mword 64) %s %s.'
                     % (pre, wid, off, pc, rvc, astt))
            if width == 16:
                ex = 'ke_%04x' % w if op in LEAF_OPS else 'exec_execute_%s' % op
                L.append('  Proof using . mk_rvc %s (mword_of_int 0x%04x : mword 16)' % (pc, w))
                L.append('    (mword_of_int %s : mword 64) %s kd_%04x %s. Qed.' % (pc, astt, w, ex))
            else:
                dec = OVERRIDES[(w, 32)][1] if (w, 32) in OVERRIDES else 'kd_%08x' % w
                L.append('  Proof using . mk_base %s (mword_of_int 0x%08x : mword 32)' % (pc, w))
                L.append('    (mword_of_int %s : mword 64) %s %s. Qed.' % (pc, astt, dec))
            L.append('')
            n += 1
    L.append('End %s.' % os.path.basename(path)[:-2])
    body = '\n'.join(L)
    head = header(path, 'xv6\'s ' + what, pres, code_imports(fams, by), body)
    write_if_changed(path, head + '\n\n' + body + '\n')
    return n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--kernel-rocq', default='kernel-rocq')
    ap.add_argument('--iris', default='iris')
    ap.add_argument('--manifest', default='tools/code_manifest.json')
    ap.add_argument('--only', nargs='*', help='restrict to these Code files')
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()

    syms = load_syms(os.path.join(args.kernel_rocq, 'KernelSyms.v'))
    by = load_bytes(os.path.join(args.kernel_rocq, 'KernelInstrs.v'))
    man = json.load(open(args.manifest))

    # THE PREFIX COLUMN MUST BE UNIQUE PER FUNCTION, and nothing downstream
    # notices if it is not: two functions sharing a prefix produce two
    # `<pre>_00` lemmas that differ only by which Code file a proof imported
    # last, so the proof silently steps the WRONG function's instruction.
    # (`printk`/`printkinit` both had `pki_`; `kexit`/`kexec` both had `kxi_`.)
    #
    # A WARNING, NOT AN ERROR, and deliberately: the check finds ~20 rows that
    # predate it, none of them currently reachable -- a collision only bites a
    # proof that imports BOTH colliding `Code<F>.v` files, and a caller uses
    # its callees' Specs, not their Code.  Failing here would block every
    # regeneration on a 20-prefix rename sweep that nothing is asking for.
    # Read the list when you add a row: yours is the one at the bottom.
    seen = {}
    dups = []
    for row in man:
        if row[2] in seen and seen[row[2]] != row[1]:
            dups.append((row[2], seen[row[2]], row[1]))
        seen.setdefault(row[2], row[1])
    if dups:
        print("WARNING: %d duplicate lemma prefixes in %s "
              "(latent unless one proof imports both):" % (len(dups), args.manifest))
        for pre, a, b in dups:
            print("   %-8s shared by %s and %s" % (pre, a, b))

    starts = sorted(set(a for a in syms.values() if a in by))
    end = max(by) + 1

    def rng(sym):
        a = syms[sym]
        i = starts.index(a)
        return a, (starts[i + 1] if i + 1 < len(starts) else end)

    groups = {}
    for row in man:
        f, sym, pre, wid = row[0], row[1], row[2], row[3]
        lo, hi = rng(sym)
        groups.setdefault(f, []).append((sym, pre, lo, hi, wid))
    # The decode shards are keyed by WORD over the whole covered set, so they
    # must always be computed from every group -- restricting to --only and
    # then emitting them would rewrite each shard with just that function's
    # handful of words and silently delete everyone else's.
    all_groups = groups
    if args.only:
        groups = {k: v for k, v in groups.items() if k in args.only}

    decoded, undec = {}, []
    for fams in all_groups.values():
        for _, _, lo, hi, _ in fams:
            for a, w, width in instructions(by, lo, hi):
                if (w, width) in decoded:
                    continue
                d = decode(w, width)
                if d is None:
                    undec.append((a, w, width))
                else:
                    decoded[(w, width)] = d
    if undec:
        print("UNDECODABLE words: %d" % len(undec))
        for a, w, width in undec[:20]:
            print("   0x%08x  0x%0*x (%d-bit)" % (a, width // 4, w, width))
        return 1

    print("covered files %d, functions %d, distinct words %d"
          % (len(groups), sum(len(v) for v in groups.values()), len(decoded)))
    if args.dry_run:
        return 0

    ncst, wrote = gen_consts.emit(args.iris, syms, by,
                                  lambda a, n: word_at(by, a, n))
    print("KernelConsts.v: %d image constants%s"
          % (ncst, "" if wrote else " (unchanged)"))

    nc, nb = emit_decode_file(decoded, args.iris)
    print("KernelDecode.v: %d compressed + %d base decode lemmas%s"
          % (nc, nb, " (all files, --only restricts the Code files only)"
             if args.only else ""))
    tot = 0
    for f, fams in sorted(groups.items()):
        tot += emit_code_file(os.path.join(args.iris, f), fams, syms, by, decoded)
    print("%d Code files, %d instr facts" % (len(groups), tot))
    return 0


if __name__ == '__main__':
    sys.exit(main())
