#!/usr/bin/env python3
"""Dump the xv6 kernel ELF's LOADED FILE IMAGE into MachCSL/KernelElf.lean.

The kernel links as ONE PT_LOAD segment; its file bytes `[vaddr, vaddr +
filesz)` (.text, .rodata, .eh_frame, .data, .got, .got.plt and the padding
between them) are what the loader puts in RAM; `.bss` (up to vaddr + memsz)
and the rest of RAM are zero.  This is the language constant the power-on
arm reloads (MachCSL.bootImage; Rocq `RiscvLang.boot_image`, which is the
same bytes, filtered below `img_end`).

Encoding: rows of 32 bytes, each ONE big-endian hex `Nat` (so a row reads like
a hexdump line), 128 rows (4 KiB) to a page.  A byte lookup is two short list
walks and a shift, cheap for `decide +kernel` (GMP-accelerated `Nat`).

Usage (from the repo root): tools/dump_elf_image.py [--kernel PATH] [--out PATH] [--rev REV]
The default kernel is the repo's `xv6-riscv/kernel/kernel`; the header
records the path as given.  Part of the kernel rebase pipeline: rerun it
whenever tools/dump_kernel.py / tools/gen_kernel_data.py are rerun.
The kernel must be the SAME build as Xv6/KernelImage.lean and
Xv6/KernelData.lean: `Xv6.bootImage_wf` checks the text, rodata and data
dumps byte for byte against this image, so a mismatch fails the build.
"""
import argparse, hashlib, os, struct

ROW, PAGE_ROWS = 32, 128

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--kernel', default='xv6-riscv/kernel/kernel')
    ap.add_argument('--out', default='MachCSL/KernelElf.lean')
    ap.add_argument('--rev', default='unknown', help='the xv6-riscv commit the kernel was built from')
    a = ap.parse_args()
    elf = open(a.kernel, 'rb').read()
    assert elf[:4] == b'\x7fELF' and elf[4] == 2 and elf[5] == 1, 'expects a little-endian ELF64'
    e_phoff, = struct.unpack_from('<Q', elf, 0x20)
    e_phentsize, e_phnum = struct.unpack_from('<HH', elf, 0x36)
    loads = []
    for i in range(e_phnum):
        p_type, _flags, off, vaddr, _paddr, filesz, memsz, _align = struct.unpack_from('<IIQQQQQQ', elf, e_phoff + i * e_phentsize)
        if p_type == 1:
            loads.append((vaddr, off, filesz, memsz))
    assert len(loads) == 1, 'expects exactly one PT_LOAD segment'
    vaddr, off, filesz, memsz = loads[0]
    data = elf[off:off + filesz]
    data += b'\0' * ((-len(data)) % ROW)
    rows = [data[i:i + ROW] for i in range(0, len(data), ROW)]
    pages = [rows[i:i + PAGE_ROWS] for i in range(0, len(rows), PAGE_ROWS)]
    md5 = hashlib.md5(elf).hexdigest()
    with open(a.out, 'w') as f:
        f.write('-- AUTO-GENERATED by tools/dump_elf_image.py from %s (xv6-riscv %s, md5 %s); do not edit.\n'
                % (a.kernel, a.rev, md5))
        f.write('''/-
THE KERNEL'S LOADED IMAGE (Rocq `KernelInstrs.kernel_bytes` and
`KernelData.kernel_data`): the file bytes of the kernel ELF's one PT_LOAD
segment, `[elfBase, elfEnd)` = .text, .rodata, .eh_frame, .data, .got,
.got.plt and the padding between them.  `.bss` (`[elfEnd, elfMemEnd)`) and the
rest of RAM are zero.  `MachCSL.bootImage` (the language's power-on memory) is
built from `elfByte`.

Rows of 32 bytes, each one big-endian hex `Nat` (it reads like a hexdump
line: the first byte is the leftmost pair of digits), 128 rows to a page.
Nothing here may be unfolded by a tactic other than `decide +kernel`.
-/

namespace MachCSL.KernelElf

''')
        f.write('/-- The segment\'s load address. -/\ndef elfBase : Nat := 0x%x\n' % vaddr)
        f.write('/-- One past its last FILE byte (Rocq `img_end`: vaddr + filesz). -/\ndef elfEnd : Nat := 0x%x\n' % (vaddr + filesz))
        f.write('/-- One past its last byte in memory (vaddr + memsz; `.bss` included). -/\ndef elfMemEnd : Nat := 0x%x\n\n' % (vaddr + memsz))
        for n, pg in enumerate(pages):
            f.write('def page%d : List Nat := [\n' % n)
            lines = []
            for r, row in enumerate(pg):
                addr = vaddr + (n * PAGE_ROWS + r) * ROW
                lines.append('  0x%s  -- %08x' % (row.hex(), addr))
            # the comment must follow the comma
            out = []
            for i, l in enumerate(lines):
                num, cmt = l.split('  -- ')
                out.append(num + (',' if i + 1 < len(lines) else '') + '  -- ' + cmt)
            f.write('\n'.join(out) + '\n]\n\n')
        f.write('/-- The image, page by page. -/\ndef pages : List (List Nat) := [%s]\n\n'
                % ', '.join('page%d' % n for n in range(len(pages))))
        f.write('''/-- Byte `j` (`j < 32`) of a big-endian row. -/
def rowByte (row j : Nat) : Nat := (row >>> (8 * (31 - j))) % 256

/-- The image byte at offset `off` from `elfBase` (zero past the dump). -/
def elfByte (off : Nat) : Nat :=
  rowByte ((pages.getD (off / 4096) []).getD (off % 4096 / 32) 0) (off % 32)

end MachCSL.KernelElf
''')
    print('%s: %d bytes [0x%x, 0x%x), memsz end 0x%x, %d pages' % (a.out, filesz, vaddr, vaddr + filesz, vaddr + memsz, len(pages)))

if __name__ == '__main__':
    main()
