#!/usr/bin/env python3
"""Emit Xv6/KernelTree.lean: the kernel text as a balanced binary search tree
keyed by address (`Kernel.textTree`), so an instruction's bytes are found by
O(log n) comparisons when a proof evaluates a lookup by `rfl`.  Built from the
instruction list of Xv6/KernelImage.lean (run after tools/dump_kernel.py);
`KernelText.lean` proves `textTree.toList = Kernel.text` once.

Usage: tools/gen_text_tree.py [--image Xv6/KernelImage.lean] [--out Xv6/KernelTree.lean] [--chunk 512]
"""
import argparse, re

ENTRY_RE = re.compile(r'^\s*⟨(0x[0-9a-f]+), (\d+), (0x[0-9a-f]+)⟩,?\s*$')

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--image', default='Xv6/KernelImage.lean')
    ap.add_argument('--out', default='Xv6/KernelTree.lean')
    ap.add_argument('--chunk', type=int, default=512)
    a = ap.parse_args()
    entries = []
    for line in open(a.image):
        m = ENTRY_RE.match(line)
        if m:
            entries.append((m.group(1), m.group(2), m.group(3)))
    assert entries, 'no instructions found'
    defs = []

    def lit(lo, hi):  # balanced tree literal over entries[lo:hi]
        if lo >= hi:
            return 'leaf'
        mid = (lo + hi) // 2
        ad, w, e = entries[mid]
        return '(node %s ⟨%s, %s, %s⟩ %s)' % (lit(lo, mid), ad, w, e, lit(mid + 1, hi))

    def build(lo, hi):
        if hi - lo <= a.chunk:
            name = 'textTree%d' % len(defs)
            defs.append((name, lit(lo, hi)))
            return name
        mid = (lo + hi) // 2
        left = build(lo, mid)
        right = build(mid + 1, hi)
        ad, w, e = entries[mid]
        return '(node %s ⟨%s, %s, %s⟩ %s)' % (left, ad, w, e, right)

    top = build(0, len(entries))
    with open(a.out, 'w') as f:
        f.write('-- AUTO-GENERATED by tools/gen_text_tree.py from %s; do not edit.\n' % a.image)
        f.write('-- The kernel text as an address-keyed balanced search tree (see KernelText.lean).\n')
        f.write('import Xv6.KernelImage\n\nnamespace Xv6.Kernel\n\n')
        f.write('/-- A binary search tree of instructions keyed by address. -/\n')
        f.write('inductive TextTree where\n  | leaf\n  | node (l : TextTree) (k : KInstr) (r : TextTree)\n\n')
        f.write('/-- The instruction at address `a`. -/\n')
        f.write('def TextTree.find? : TextTree → Nat → Option KInstr\n  | .leaf, _ => none\n  | .node l k r, a =>\n'
                '    if a < k.addr then l.find? a else if k.addr < a then r.find? a else some k\n\n')
        f.write('/-- In-order traversal (address order). -/\n')
        f.write('def TextTree.toList : TextTree → List KInstr\n  | .leaf => []\n  | .node l k r => l.toList ++ k :: r.toList\n\n')
        f.write('open TextTree in\nsection\nset_option maxRecDepth 4096\n\n')
        for name, body in defs:
            f.write('def %s : TextTree :=\n  %s\n\n' % (name, body))
        f.write('/-- All %d instructions of the kernel text, searchable by address. -/\n' % len(entries))
        f.write('def textTree : TextTree :=\n  %s\n\nend\n\nend Xv6.Kernel\n' % top)
    print('wrote %s: %d instructions, %d subtrees' % (a.out, len(entries), len(defs)))

if __name__ == '__main__':
    main()
