(* QEMU/PtResvPass.v -- GENERATED by tools/vtest.  Do not edit.

   The proof for the run of case [pt_resv] on platform [qemu].  What is proved
   is a statement about [RiscvLang.prim_step]; [VExecStep] is what carries a
   computation of the interpreter to it.

   THIS RUN PASSES BECAUSE the model EXHIBITS every observation the platform
   produced, from this test's own configuration. *)
From Stdlib Require Import List ZArith.
From stdpp Require Import base list.
Import ListNotations.
From VTest Require Import VTest VRun VExecStep.
From VTest.QEMU Require Import PtResvTest PtResvRun.

Module PtResvPass <: TEST_PASSES_AGREE PtResv PtResvRun.
  Lemma agrees :
    run_agrees PtResv.hart PtResv.text PtResv.regions
               PtResv.uart_input PtResv.disk_init PtResvRun.observed.
  Proof.
    intros o Ho.
    cbn [PtResvRun.observed PtResvRun.results fmap list_fmap] in Ho.
    repeat (destruct Ho as [<-|Ho];
            [ apply (run_shows false lowest_head 2000 2000);
              vm_cast_no_check (eq_refl true) |]).
    destruct Ho.
  Qed.
End PtResvPass.
