(* QEMU/UartRxPass.v -- GENERATED by tools/vtest.  Do not edit.

   The proof for the run of case [uart_rx] on platform [qemu].  What is proved
   is a statement about [RiscvLang.prim_step]; [VExecStep] is what carries a
   computation of the interpreter to it.

   THIS RUN PASSES BECAUSE the model EXHIBITS every observation the platform
   produced, from this test's own configuration. *)
From Stdlib Require Import List ZArith.
From stdpp Require Import base list.
Import ListNotations.
From VTest Require Import VTest VRun VExecStep.
From VTest.QEMU Require Import UartRxTest UartRxRun.

Module UartRxPass <: TEST_PASSES_AGREE UartRx UartRxRun.
  Lemma agrees :
    run_agrees UartRx.hart UartRx.text UartRx.regions
               UartRx.uart_input UartRx.disk_init UartRxRun.observed.
  Proof.
    intros o Ho.
    cbn [UartRxRun.observed UartRxRun.results fmap list_fmap] in Ho.
    repeat (destruct Ho as [<-|Ho];
            [ apply (run_shows false lowest_head 50000 50000);
              vm_cast_no_check (eq_refl true) |]).
    destruct Ho.
  Qed.
End UartRxPass.
