(* QEMU/Uart1TxPass.v -- GENERATED by tools/vtest.  Do not edit.

   The proof for the run of case [uart1_tx] on platform [qemu].  What is proved
   is a statement about [RiscvLang.prim_step]; [VExecStep] is what carries a
   computation of the interpreter to it.

   THIS RUN PASSES BECAUSE the model EXHIBITS every observation the platform
   produced, from this test's own configuration. *)
From Stdlib Require Import List ZArith.
From stdpp Require Import base list.
Import ListNotations.
From VTest Require Import VTest VRun VExecStep.
From VTest.QEMU Require Import Uart1TxTest Uart1TxRun.

Module Uart1TxPass <: TEST_PASSES_AGREE Uart1Tx Uart1TxRun.
  Lemma agrees :
    run_agrees Uart1Tx.hart Uart1Tx.text Uart1Tx.regions
               Uart1Tx.uart_input Uart1Tx.disk_init Uart1TxRun.observed.
  Proof.
    intros o Ho.
    cbn [Uart1TxRun.observed Uart1TxRun.results fmap list_fmap] in Ho.
    repeat (destruct Ho as [<-|Ho];
            [ apply (run_shows false lowest_head 2000 2000);
              vm_cast_no_check (eq_refl true) |]).
    destruct Ho.
  Qed.
End Uart1TxPass.
